In [363]:
import scvi
import torch
import numpy as np
from pathlib import Path
import pandas as pd
from modules.utils import dict_summary, capture_kwargs
import inspect
from typing import Literal
import scipy

In [2]:
import modules.data as d
import modules.utils as u
from pathlib import Path

#### init ####
dataset_dir = Path('/home/mv18gs/Documents/GitHub/pathway_model/datasets/')
device = u.Devices().auto_set_device(drop=['cuda:4'])

#### data ####
brca = d.TCGA(
    tcga_project = 'BRCA',
    tcga_dir = dataset_dir/'tcga',
    # type_col = 'sample_type',
    subtype_col = 'paper_BRCA_Subtype_PAM50',
    drop = ['Normal', 'Primary Tumor', 'Metastatic'],
    gene_name_path = dataset_dir/'other'/'name2ensg.csv',
    keep_noname = False,
)

kegg = d.KEGG(
    relation_filepath=dataset_dir/'other'/'relation_ohe.csv', 
    counts_data=brca,
)

dataset = d.GraphDataset(brca, kegg, kegg)
_batch = d.get_toy_databatch(dataset, device)

('cuda:6', 'NVIDIA A100-SXM4-80GB', 81043)
('cuda:2', 'NVIDIA A100-SXM4-80GB', 81041)
('cuda:3', 'NVIDIA A100-SXM4-80GB', 81041)
('cuda:7', 'NVIDIA A100-SXM4-80GB', 81041)
('cuda:0', 'NVIDIA A100-SXM4-80GB', 78521)
('cuda:5', 'NVIDIA A100-SXM4-80GB', 74623)
('cuda:4', 'NVIDIA A100-SXM4-80GB', 64631)
('cuda:1', 'NVIDIA A100-SXM4-80GB', 56563)

# #### Device() ####
# device = cuda:6

# #### KEGG() ####
# _orig_kwargs             5                        dict
# relation                 (75939, 19)              DataFrame
# ensg                     4373                     list
# pathway_labels           305                      list
# edge_index               (2, 32464)               Tensor (cuda:6)
# edge_attr                (32464, 16)              Tensor (cuda:6)
# edge_labels              16                       list
# pathway_index            (4373, 305)              Tensor (cuda:6)

# #### TCGA() ####
# _orig_kwargs             9                        dict
# counts_path              PosixPath
# metadata_path            PosixPath
# gene_name_path           PosixPath
# metadata_complete        (1231, 93)               DataFrame
# metadata                 (1172, 2)                DataFrame
# y                        (1172,)                  Tensor (cuda:6)
# y_labels                 5                        list
# ensgv                    (60660, 3)               DataFrame
# ensg_complete            19213                    list
# counts                   (1172, 4373)             DataFrame
# x                        (1172, 4373, 1)          Tensor (cuda:6)
# x_labels                 4373                     list

# #### DataWrapper() ####
# counts_params            9                        dict
# edge_params              5                        dict
# pathway_params           NoneType
# x                        (1172, 4373, 1)          Tensor (cuda:6)
# y                        (1172,)                  Tensor (cuda:6)
# x_labels                 4373                     list
# y_labels                 5                        list
# edge_index               (2, 32464)               Tensor (cuda:6)
# edge_attr                (32464, 16)              Tensor (cuda:6)
# edge_labels              16                       list
# pathway_index            (4373, 305)              Tensor (cuda:6)
# pathway_labels           305                      list
# num_samples              1172                     int
# num_nodes                4373                     int
# num_node_features        1                        int
# num_classes              5                        int
# num_edges                32464                    int
# num_edge_features        16                       int
# num_pathways             305                      int


# #### GraphDataset(), Summary ####
# Average node degree      0.1347                   float
# Has isolated nodes       True                     bool
# Has self-loops           True                     bool
# Directionality           directed                 str

In [3]:
cortex = scvi.data.cortex(dataset_dir / 'scvi' / 'cortex')

INFO     File /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/cortex/expression.bin already downloaded
INFO     Loading Cortex data from /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/cortex/expression.bin
INFO     Finished loading Cortex data

/home/mv18gs/miniconda3/envs/thesis_scvi/lib/python3.14/functools.py:982: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

In [4]:
pbmc = scvi.data.pbmc_dataset(dataset_dir / 'scvi' / 'pbmc_dataset')

INFO     File /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/gene_info_pbmc.csv already
         downloaded
INFO     File /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc_metadata.pickle already
         downloaded
INFO     File
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc8k/filtered_gene_bc_matrices.ta
         r.gz already downloaded
INFO     Extracting tar file
INFO     Removing extracted data at
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc8k/filtered_gene_bc_matrices
INFO     File
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc4k/filtered_gene_bc_matrices.ta
         r.gz already downloaded
INFO     Extracting tar file
INFO     Removing extracted data at
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc4k/filtered_gene_bc_matrices

/home/mv18gs/miniconda3/envs/thesis_scvi/lib/python3.14/site-packages/scvi/data/_built_in_data/_pbmc.py:75: FutureWarning: Use anndata.concat instead of AnnData.concatenate, AnnData.concatenate is deprecated and will be removed in the future. See the tutorial for concat at: https://anndata.readthedocs.io/en/latest/concatenation.html
  adata = pbmc8k.concatenate(pbmc4k)

In [5]:
breast = scvi.data.breast_cancer_dataset(dataset_dir / 'scvi' / 'breast_cancer_dataset')

INFO     File
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/breast_cancer_dataset/Layer2_BC_count_matrix-1.t
         sv already downloaded
INFO     Loading dataset from
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/breast_cancer_dataset/Layer2_BC_count_matrix-1.t
         sv
INFO     Finished loading dataset

In [6]:
cortex

AnnData object with n_obs × n_vars = 3005 × 19972
    obs: 'labels', 'precise_labels', 'cell_type'

In [7]:
pbmc

AnnData object with n_obs × n_vars = 11990 × 3346
    obs: 'n_counts', 'batch', 'labels', 'str_labels'
    var: 'gene_symbols', 'n_counts-0', 'n_counts-1', 'n_counts'
    uns: 'cell_types'
    obsm: 'design', 'raw_qc', 'normalized_qc', 'qc_pc'

In [8]:
pbmc

AnnData object with n_obs × n_vars = 11990 × 3346
    obs: 'n_counts', 'batch', 'labels', 'str_labels'
    var: 'gene_symbols', 'n_counts-0', 'n_counts-1', 'n_counts'
    uns: 'cell_types'
    obsm: 'design', 'raw_qc', 'normalized_qc', 'qc_pc'

In [9]:
pbmc

AnnData object with n_obs × n_vars = 11990 × 3346
    obs: 'n_counts', 'batch', 'labels', 'str_labels'
    var: 'gene_symbols', 'n_counts-0', 'n_counts-1', 'n_counts'
    uns: 'cell_types'
    obsm: 'design', 'raw_qc', 'normalized_qc', 'qc_pc'

In [10]:
torch.tensor(cortex.X)

tensor([[0, 3, 3,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 6,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:6', dtype=torch.int32)

In [11]:
torch.tensor(pbmc.X.toarray())

tensor([[0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [2., 2., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:6')

In [12]:
cortex.__dict__

{'_is_view': False,
 '_adata_ref': None,
 '_oidx': None,
 '_vidx': None,
 'file': Backing file manager: no file is set.,
 '_X': array([[0, 3, 3, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0],
        [0, 0, 6, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 0]], shape=(3005, 19972), dtype=int32),
 '_obs':       labels  precise_labels          cell_type
 0          2               0       interneurons
 1          2               0       interneurons
 2          2               0       interneurons
 3          2               0       interneurons
 4          2               0       interneurons
 ...      ...             ...                ...
 3000       1               8  endothelial-mural
 3001       1               8  endothelial-mural
 3002       1               8  endothelial-mural
 3003       1               8  endothelial-mural
 3004       1               8  endothelial-mural

 [3005 rows x 3 columns],
 '_var': Empty DataFrame
 Columns: []
 Index: [Tspan12, Tshz1, Fnbp1l, Adamts15, Cldn12, Rxfp1, 2310042E22Rik, Sema3c, Jam2, Apbb1ip, Frem2, BC005764, Deptor, C130030K03Rik, Klhl13, Tnfaip8l3, Ascl1, Atp1b2, Tmem132e, Prkar2b, Necab1, Nr2f2, Stmn1-rs1, Shisa9, Sub1, Vat1l, Pcdh18, Dpysl5, Agtr2, Cxcl14, Ptprf, Cers5, Nacc2, Cntnap2, Asic4, Tph2, Rit2, Scg2, Nr2e1, Bmp3, B3galnt1, Gm9846, Kcnn1, Fam19a2, Samd4, Stmn1, Egln3, Bmper, Cd200, 1810041L15Rik, Rnf128, P2ry1, Sorcs1, Htr3a, Kcnip1, Sco2, 2610044O15Rik8, Tmem41b, Cdh9, Ppp2r3d, Usp28, Trib2, L2hgdh, Cited2, Btbd11, Rgs12, Cnr1, Kcnd3, Htr3b, Sulf2, Capn5, Osbpl5, Nrtn, Nr2f1, Galnt14, Slc35f1, Mmgt1, Htr7, E130309F12Rik, Wtap, Racgap1, Arhgap24, Maml3, Gng2, Tnc, Fndc3a, Npas3, Celf6, Inpp4b, Npas1, Ache, Clnk, Sel1l3, Adarb2, Nrxn3, Fam211b, Akap7, Chrna4, Ugp2, Tmem242, ...]

 [19972 rows x 0 columns],
 '_uns': OrderedDict(),
 '_obsm': {},
 '_varm': {},
 '_obsp': {},
 '_varp': {},
 '_raw': None,
 '_layers': {}}

In [54]:
cortex.X.shape

(3005, 19972)

In [50]:
len(cortex.var.index.to_list())

19972

* TCGA Output:
    * x: counts tensor in (batch, genes)
    * x_labels: list of gene names in len(genes)
    * y: label tensor (int) in (batch,)
    * y_labels: list of class names in len(classes,)

* scVI output:
    * var.index.to_list(): x_labels (unfiltered)

provided:
    * int array 'X' in shape (samples, genes)
    * pd index 'names' with len (genes)
    * df 'name2ensg' with str cols ['ensg', 'name']
    * optional list 'ensg_filter'

filter out 'names' which do not have a corresponding name2ensg['name'] (non-case sensitive) in name2ensg['ensg'], 
and optionally, do not have a name2ensg['ensg'] in ensg_filter if provided.

In [41]:
brca.y_labels

['Basal', 'Her2', 'LumA', 'LumB', 'Solid Tissue Normal']

In [38]:
len(brca.x_labels)

4373

In [61]:
kegg.ensg

['ENSG00000000938',
 'ENSG00000001084',
 'ENSG00000001167',
 'ENSG00000001617',
 'ENSG00000001626',
 'ENSG00000001630',
 'ENSG00000001631',
 'ENSG00000002330',
 'ENSG00000002549',
 'ENSG00000002726',
 'ENSG00000003056',
 'ENSG00000003137',
 'ENSG00000003393',
 'ENSG00000003400',
 'ENSG00000003402',
 'ENSG00000003987',
 'ENSG00000004139',
 'ENSG00000004455',
 'ENSG00000004468',
 'ENSG00000004487',
 'ENSG00000004660',
 'ENSG00000004779',
 'ENSG00000004799',
 'ENSG00000004897',
 'ENSG00000004961',
 'ENSG00000004975',
 'ENSG00000005007',
 'ENSG00000005022',
 'ENSG00000005100',
 'ENSG00000005187',
 'ENSG00000005249',
 'ENSG00000005339',
 'ENSG00000005483',
 'ENSG00000005801',
 'ENSG00000005844',
 'ENSG00000005882',
 'ENSG00000005884',
 'ENSG00000005893',
 'ENSG00000005961',
 'ENSG00000006062',
 'ENSG00000006071',
 'ENSG00000006125',
 'ENSG00000006210',
 'ENSG00000006283',
 'ENSG00000006327',
 'ENSG00000006432',
 'ENSG00000006451',
 'ENSG00000006530',
 'ENSG00000006534',
 'ENSG00000006607',
 'ENSG00000006625',
 'ENSG00000006638',
 'ENSG00000006695',
 'ENSG00000006715',
 'ENSG00000006747',
 'ENSG00000006757',
 'ENSG00000006831',
 'ENSG00000007168',
 'ENSG00000007174',
 'ENSG00000007264',
 'ENSG00000007312',
 'ENSG00000007384',
 'ENSG00000007402',
 'ENSG00000007866',
 'ENSG00000007908',
 'ENSG00000007933',
 'ENSG00000007944',
 'ENSG00000007952',
 'ENSG00000007968',
 'ENSG00000008018',
 'ENSG00000008130',
 'ENSG00000008256',
 'ENSG00000008311',
 'ENSG00000008394',
 'ENSG00000008513',
 'ENSG00000008516',
 'ENSG00000008735',
 'ENSG00000009724',
 'ENSG00000009830',
 'ENSG00000009844',
 'ENSG00000009950',
 'ENSG00000010256',
 'ENSG00000010310',
 'ENSG00000010319',
 'ENSG00000010327',
 'ENSG00000010404',
 'ENSG00000010539',
 'ENSG00000010610',
 'ENSG00000010671',
 'ENSG00000010704',
 'ENSG00000010810',
 'ENSG00000010932',
 'ENSG00000011009',
 'ENSG00000011028',
 'ENSG00000011198',
 'ENSG00000011405',
 'ENSG00000011422',
 'ENSG00000011465',
 'ENSG00000011485',
 'ENSG00000011566',
 'ENSG00000011600',
 'ENSG00000011677',
 'ENSG00000012048',
 'ENSG00000012124',
 'ENSG00000012171',
 'ENSG00000012211',
 'ENSG00000012232',
 'ENSG00000012660',
 'ENSG00000012779',
 'ENSG00000013016',
 'ENSG00000013297',
 'ENSG00000013375',
 'ENSG00000013725',
 'ENSG00000014216',
 'ENSG00000014919',
 'ENSG00000015285',
 'ENSG00000015475',
 'ENSG00000015532',
 'ENSG00000016391',
 'ENSG00000017427',
 'ENSG00000017797',
 'ENSG00000018236',
 'ENSG00000018408',
 'ENSG00000018625',
 'ENSG00000018869',
 'ENSG00000019186',
 'ENSG00000019549',
 'ENSG00000019582',
 'ENSG00000019991',
 'ENSG00000020633',
 'ENSG00000020922',
 'ENSG00000021645',
 'ENSG00000021762',
 'ENSG00000021826',
 'ENSG00000023228',
 'ENSG00000023287',
 'ENSG00000023330',
 'ENSG00000023445',
 'ENSG00000023697',
 'ENSG00000023909',
 'ENSG00000025039',
 'ENSG00000025423',
 'ENSG00000025434',
 'ENSG00000025708',
 'ENSG00000026025',
 'ENSG00000026103',
 'ENSG00000026508',
 'ENSG00000026652',
 'ENSG00000027075',
 'ENSG00000027697',
 'ENSG00000027847',
 'ENSG00000027869',
 'ENSG00000028137',
 'ENSG00000028277',
 'ENSG00000028839',
 'ENSG00000029534',
 'ENSG00000030110',
 'ENSG00000031698',
 'ENSG00000032444',
 'ENSG00000033011',
 'ENSG00000033050',
 'ENSG00000033100',
 'ENSG00000033170',
 'ENSG00000033327',
 'ENSG00000033627',
 'ENSG00000033800',
 'ENSG00000034152',
 'ENSG00000034713',
 'ENSG00000035403',
 'ENSG00000035664',
 'ENSG00000035681',
 'ENSG00000035687',
 'ENSG00000036257',
 'ENSG00000036530',
 'ENSG00000037280',
 'ENSG00000037757',
 'ENSG00000038210',
 'ENSG00000038274',
 'ENSG00000039068',
 'ENSG00000039139',
 'ENSG00000039319',
 'ENSG00000039537',
 'ENSG00000040199',
 'ENSG00000040933',
 'ENSG00000041357',
 'ENSG00000041880',
 'ENSG00000041982',
 'ENSG00000042286',
 'ENSG00000042445',
 'ENSG00000042753',
 'ENSG00000043462',
 'ENSG00000043591',
 'ENSG00000044115',
 'ENSG00000044446',
 'ENSG00000044524',
 'ENSG00000044574',
 'ENSG00000046604',
 'ENSG00000047230',
 'ENSG00000047249',
 'ENSG00000047410',
 'ENSG00000047457',
 'ENSG00000048392',
 'ENSG00000048462',
 'ENSG00000049089',
 'ENSG00000049130',
 'ENSG00000049239',
 'ENSG00000049246',
 'ENSG00000049249',
 'ENSG00000049323',
 'ENSG00000049618',
 'ENSG00000049759',
 'ENSG00000049768',
 'ENSG00000049769',
 'ENSG00000049860',
 'ENSG00000050555',
 'ENSG00000050628',
 'ENSG00000050748',
 'ENSG00000050820',
 'ENSG00000051128',
 'ENSG00000051180',
 'ENSG00000051382',
 'ENSG00000051523',
 'ENSG00000052723',
 'ENSG00000052795',
 'ENSG00000052802',
 'ENSG00000053747',
 'ENSG00000053900',
 'ENSG00000053918',
 'ENSG00000054179',
 'ENSG00000054983',
 'ENSG00000055130',
 'ENSG00000055208',
 'ENSG00000055332',
 'ENSG00000055609',
 'ENSG00000055917',
 'ENSG00000056558',
 'ENSG00000056736',
 'ENSG00000056972',
 'ENSG00000056998',
 'ENSG00000057252',
 'ENSG00000057663',
 'ENSG00000058063',
 'ENSG00000058085',
 'ENSG00000058272',
 'ENSG00000058335',
 'ENSG00000058404',
 'ENSG00000058668',
 'ENSG00000058866',
 'ENSG00000059377',
 'ENSG00000059573',
 'ENSG00000059691',
 'ENSG00000060138',
 'ENSG00000060237',
 'ENSG00000060558',
 'ENSG00000060642',
 'ENSG00000060971',
 'ENSG00000060982',
 'ENSG00000061455',
 'ENSG00000061918',
 'ENSG00000062038',
 'ENSG00000062282',
 'ENSG00000062370',
 'ENSG00000062485',
 'ENSG00000062598',
 'ENSG00000062716',
 'ENSG00000063046',
 'ENSG00000063176',
 'ENSG00000063587',
 'ENSG00000063601',
 'ENSG00000063660',
 'ENSG00000063854',
 'ENSG00000064012',
 'ENSG00000064225',
 'ENSG00000064300',
 'ENSG00000064309',
 'ENSG00000064393',
 'ENSG00000064419',
 'ENSG00000064490',
 'ENSG00000064547',
 'ENSG00000064601',
 'ENSG00000064651',
 'ENSG00000064692',
 'ENSG00000064989',
 'ENSG00000065029',
 'ENSG00000065135',
 'ENSG00000065154',
 'ENSG00000065243',
 'ENSG00000065357',
 'ENSG00000065361',
 'ENSG00000065518',
 'ENSG00000065526',
 'ENSG00000065534',
 'ENSG00000065559',
 'ENSG00000065613',
 'ENSG00000065621',
 'ENSG00000065675',
 'ENSG00000065717',
 'ENSG00000065833',
 'ENSG00000065882',
 'ENSG00000065911',
 'ENSG00000065989',
 'ENSG00000066027',
 'ENSG00000066044',
 'ENSG00000066117',
 'ENSG00000066136',
 'ENSG00000066248',
 'ENSG00000066322',
 'ENSG00000066336',
 'ENSG00000066427',
 'ENSG00000066468',
 'ENSG00000066739',
 'ENSG00000066926',
 'ENSG00000067057',
 'ENSG00000067064',
 'ENSG00000067113',
 'ENSG00000067141',
 'ENSG00000067177',
 'ENSG00000067182',
 'ENSG00000067191',
 'ENSG00000067225',
 'ENSG00000067369',
 'ENSG00000067560',
 'ENSG00000067606',
 'ENSG00000067829',
 'ENSG00000067900',
 'ENSG00000067992',
 'ENSG00000068001',
 'ENSG00000068024',
 'ENSG00000068028',
 'ENSG00000068078',
 'ENSG00000068120',
 'ENSG00000068305',
 'ENSG00000068308',
 'ENSG00000068323',
 'ENSG00000068366',
 'ENSG00000068383',
 'ENSG00000068650',
 'ENSG00000068745',
 'ENSG00000068831',
 'ENSG00000068903',
 'ENSG00000068971',
 'ENSG00000068976',
 'ENSG00000069399',
 'ENSG00000069509',
 'ENSG00000069535',
 'ENSG00000069667',
 'ENSG00000069849',
 'ENSG00000069869',
 'ENSG00000069943',
 'ENSG00000069956',
 'ENSG00000069966',
 'ENSG00000070010',
 'ENSG00000070018',
 'ENSG00000070087',
 'ENSG00000070190',
 'ENSG00000070193',
 'ENSG00000070214',
 'ENSG00000070366',
 'ENSG00000070371',
 'ENSG00000070501',
 'ENSG00000070526',
 'ENSG00000070540',
 'ENSG00000070610',
 'ENSG00000070731',
 'ENSG00000070756',
 'ENSG00000070770',
 'ENSG00000070831',
 'ENSG00000070886',
 'ENSG00000070961',
 'ENSG00000071051',
 'ENSG00000071054',
 'ENSG00000071073',
 'ENSG00000071205',
 'ENSG00000071242',
 'ENSG00000071553',
 'ENSG00000071564',
 'ENSG00000071626',
 'ENSG00000072042',
 'ENSG00000072062',
 'ENSG00000072110',
 'ENSG00000072133',
 'ENSG00000072210',
 'ENSG00000072274',
 'ENSG00000072310',
 'ENSG00000072364',
 'ENSG00000072415',
 'ENSG00000072506',
 'ENSG00000072682',
 'ENSG00000072694',
 'ENSG00000072736',
 'ENSG00000072778',
 'ENSG00000072803',
 'ENSG00000072840',
 'ENSG00000072952',
 'ENSG00000072958',
 'ENSG00000073008',
 'ENSG00000073350',
 'ENSG00000073417',
 'ENSG00000073578',
 'ENSG00000073584',
 'ENSG00000073711',
 'ENSG00000073737',
 'ENSG00000073756',
 'ENSG00000073803',
 'ENSG00000073849',
 'ENSG00000073861',
 'ENSG00000073969',
 'ENSG00000074047',
 'ENSG00000074181',
 'ENSG00000074211',
 'ENSG00000074219',
 'ENSG00000074319',
 'ENSG00000074370',
 'ENSG00000074416',
 'ENSG00000074660',
 'ENSG00000074696',
 'ENSG00000074800',
 'ENSG00000075073',
 'ENSG00000075213',
 'ENSG00000075218',
 'ENSG00000075223',
 'ENSG00000075239',
 'ENSG00000075388',
 'ENSG00000075391',
 'ENSG00000075407',
 'ENSG00000075426',
 'ENSG00000075461',
 'ENSG00000075624',
 'ENSG00000075643',
 'ENSG00000075651',
 'ENSG00000075711',
 'ENSG00000075785',
 'ENSG00000075826',
 'ENSG00000075886',
 'ENSG00000076258',
 'ENSG00000076356',
 'ENSG00000076555',
 'ENSG00000076604',
 'ENSG00000076685',
 'ENSG00000076716',
 'ENSG00000076864',
 'ENSG00000076928',
 'ENSG00000076984',
 'ENSG00000077044',
 'ENSG00000077150',
 'ENSG00000077157',
 'ENSG00000077238',
 'ENSG00000077264',
 'ENSG00000077420',
 'ENSG00000077463',
 'ENSG00000077782',
 'ENSG00000077943',
 'ENSG00000078061',
 'ENSG00000078070',
 'ENSG00000078124',
 'ENSG00000078142',
 'ENSG00000078237',
 'ENSG00000078269',
 'ENSG00000078295',
 'ENSG00000078304',
 'ENSG00000078369',
 'ENSG00000078401',
 'ENSG00000078549',
 'ENSG00000078668',
 'ENSG00000078747',
 'ENSG00000078804',
 'ENSG00000078900',
 'ENSG00000079102',
 'ENSG00000079277',
 'ENSG00000079332',
 'ENSG00000079337',
 'ENSG00000079435',
 'ENSG00000079459',
 'ENSG00000079462',
 'ENSG00000079739',
 'ENSG00000079805',
 'ENSG00000079841',
 'ENSG00000079950',
 'ENSG00000079999',
 'ENSG00000080503',
 'ENSG00000080546',
 'ENSG00000080815',
 'ENSG00000080819',
 'ENSG00000080824',
 'ENSG00000080839',
 'ENSG00000081026',
 'ENSG00000081041',
 'ENSG00000081051',
 'ENSG00000081052',
 'ENSG00000081059',
 'ENSG00000081181',
 'ENSG00000081189',
 'ENSG00000081237',
 'ENSG00000081248',
 'ENSG00000081386',
 'ENSG00000081479',
 'ENSG00000081665',
 'ENSG00000081760',
 'ENSG00000081913',
 'ENSG00000081985',
 'ENSG00000082014',
 'ENSG00000082175',
 'ENSG00000082212',
 'ENSG00000082258',
 'ENSG00000082458',
 'ENSG00000082482',
 'ENSG00000082512',
 'ENSG00000082701',
 'ENSG00000082781',
 'ENSG00000082898',
 'ENSG00000083093',
 'ENSG00000083123',
 'ENSG00000083290',
 'ENSG00000083444',
 'ENSG00000083457',
 'ENSG00000083720',
 'ENSG00000083750',
 'ENSG00000083799',
 'ENSG00000083807',
 'ENSG00000083812',
 'ENSG00000083814',
 'ENSG00000083817',
 'ENSG00000083828',
 'ENSG00000083844',
 'ENSG00000083937',
 'ENSG00000084073',
 'ENSG00000084093',
 'ENSG00000084112',
 'ENSG00000084207',
 'ENSG00000084674',
 'ENSG00000084733',
 'ENSG00000084754',
 'ENSG00000084774',
 'ENSG00000085117',
 'ENSG00000085231',
 'ENSG00000085276',
 'ENSG00000085377',
 'ENSG00000085415',
 'ENSG00000085511',
 'ENSG00000085514',
 'ENSG00000085662',
 'ENSG00000085733',
 'ENSG00000085741',
 'ENSG00000085871',
 'ENSG00000085978',
 'ENSG00000085998',
 'ENSG00000086062',
 'ENSG00000086065',
 'ENSG00000086102',
 'ENSG00000086205',
 'ENSG00000086232',
 'ENSG00000086475',
 'ENSG00000086544',
 'ENSG00000086619',
 'ENSG00000086696',
 'ENSG00000086730',
 'ENSG00000086758',
 'ENSG00000086848',
 'ENSG00000086991',
 'ENSG00000087008',
 'ENSG00000087053',
 'ENSG00000087074',
 'ENSG00000087077',
 'ENSG00000087085',
 'ENSG00000087086',
 'ENSG00000087088',
 'ENSG00000087095',
 'ENSG00000087157',
 'ENSG00000087237',
 'ENSG00000087245',
 'ENSG00000087253',
 'ENSG00000087258',
 'ENSG00000087266',
 'ENSG00000087460',
 'ENSG00000087470',
 'ENSG00000087494',
 'ENSG00000087586',
 'ENSG00000088002',
 'ENSG00000088035',
 'ENSG00000088256',
 'ENSG00000088280',
 'ENSG00000088305',
 'ENSG00000088766',
 'ENSG00000088826',
 'ENSG00000088827',
 'ENSG00000088833',
 'ENSG00000088876',
 'ENSG00000088888',
 'ENSG00000088899',
 'ENSG00000089012',
 'ENSG00000089022',
 'ENSG00000089053',
 'ENSG00000089127',
 'ENSG00000089159',
 'ENSG00000089163',
 'ENSG00000089234',
 'ENSG00000089248',
 'ENSG00000089289',
 'ENSG00000089335',
 'ENSG00000089472',
 'ENSG00000089597',
 'ENSG00000089685',
 'ENSG00000090013',
 'ENSG00000090020',
 'ENSG00000090054',
 'ENSG00000090266',
 'ENSG00000090339',
 'ENSG00000090376',
 'ENSG00000090432',
 'ENSG00000090447',
 'ENSG00000090539',
 'ENSG00000090612',
 'ENSG00000090621',
 'ENSG00000090659',
 'ENSG00000090661',
 'ENSG00000090776',
 'ENSG00000090863',
 'ENSG00000091073',
 'ENSG00000091106',
 'ENSG00000091129',
 'ENSG00000091136',
 'ENSG00000091140',
 'ENSG00000091409',
 'ENSG00000091428',
 'ENSG00000091436',
 'ENSG00000091483',
 'ENSG00000091513',
 'ENSG00000091592',
 'ENSG00000091831',
 'ENSG00000091879',
 'ENSG00000092010',
 'ENSG00000092020',
 'ENSG00000092054',
 'ENSG00000092439',
 'ENSG00000092445',
 'ENSG00000092621',
 'ENSG00000092758',
 'ENSG00000092820',
 'ENSG00000092841',
 'ENSG00000092964',
 'ENSG00000092969',
 'ENSG00000093010',
 'ENSG00000093072',
 'ENSG00000093144',
 'ENSG00000093217',
 'ENSG00000094755',
 'ENSG00000094804',
 'ENSG00000094880',
 'ENSG00000094963',
 'ENSG00000095015',
 'ENSG00000095203',
 'ENSG00000095303',
 'ENSG00000095380',
 'ENSG00000095539',
 'ENSG00000095585',
 'ENSG00000095637',
 'ENSG00000095739',
 'ENSG00000095794',
 'ENSG00000096063',
 'ENSG00000096384',
 'ENSG00000096433',
 'ENSG00000096654',
 'ENSG00000096717',
 'ENSG00000096968',
 'ENSG00000096996',
 'ENSG00000097007',
 'ENSG00000097021',
 'ENSG00000097033',
 'ENSG00000099194',
 'ENSG00000099204',
 'ENSG00000099250',
 'ENSG00000099365',
 'ENSG00000099377',
 'ENSG00000099381',
 'ENSG00000099624',
 'ENSG00000099769',
 'ENSG00000099795',
 'ENSG00000099797',
 'ENSG00000099810',
 'ENSG00000099860',
 'ENSG00000099875',
 'ENSG00000099940',
 'ENSG00000099942',
 'ENSG00000099956',
 'ENSG00000099968',
 'ENSG00000099998',
 'ENSG00000100030',
 'ENSG00000100033',
 'ENSG00000100055',
 'ENSG00000100060',
 'ENSG00000100065',
 'ENSG00000100077',
 'ENSG00000100078',
 'ENSG00000100116',
 'ENSG00000100150',
 'ENSG00000100167',
 'ENSG00000100219',
 'ENSG00000100234',
 'ENSG00000100246',
 'ENSG00000100280',
 'ENSG00000100285',
 'ENSG00000100290',
 'ENSG00000100292',
 'ENSG00000100294',
 'ENSG00000100299',
 'ENSG00000100300',
 'ENSG00000100311',
 'ENSG00000100324',
 'ENSG00000100330',
 'ENSG00000100344',
 'ENSG00000100345',
 'ENSG00000100346',
 'ENSG00000100347',
 'ENSG00000100348',
 'ENSG00000100351',
 'ENSG00000100365',
 'ENSG00000100368',
 'ENSG00000100385',
 'ENSG00000100387',
 'ENSG00000100393',
 'ENSG00000100412',
 'ENSG00000100417',
 'ENSG00000100422',
 'ENSG00000100448',
 'ENSG00000100453',
 'ENSG00000100485',
 'ENSG00000100504',
 'ENSG00000100522',
 'ENSG00000100554',
 'ENSG00000100567',
 'ENSG00000100577',
 'ENSG00000100592',
 'ENSG00000100596',
 'ENSG00000100600',
 'ENSG00000100603',
 'ENSG00000100605',
 'ENSG00000100614',
 'ENSG00000100626',
 'ENSG00000100644',
 'ENSG00000100650',
 'ENSG00000100714',
 'ENSG00000100721',
 'ENSG00000100726',
 'ENSG00000100764',
 'ENSG00000100784',
 'ENSG00000100796',
 'ENSG00000100804',
 'ENSG00000100852',
 'ENSG00000100888',
 'ENSG00000100889',
 'ENSG00000100902',
 'ENSG00000100906',
 'ENSG00000100911',
 'ENSG00000100918',
 'ENSG00000100934',
 'ENSG00000100938',
 'ENSG00000100968',
 'ENSG00000100983',
 'ENSG00000100985',
 'ENSG00000100994',
 'ENSG00000101017',
 'ENSG00000101049',
 'ENSG00000101057',
 'ENSG00000101096',
 'ENSG00000101104',
 'ENSG00000101109',
 'ENSG00000101144',
 'ENSG00000101158',
 'ENSG00000101160',
 'ENSG00000101182',
 'ENSG00000101210',
 'ENSG00000101224',
 'ENSG00000101255',
 'ENSG00000101265',
 'ENSG00000101266',
 'ENSG00000101282',
 'ENSG00000101290',
 'ENSG00000101307',
 'ENSG00000101310',
 'ENSG00000101333',
 'ENSG00000101335',
 'ENSG00000101336',
 'ENSG00000101347',
 'ENSG00000101365',
 'ENSG00000101384',
 'ENSG00000101407',
 'ENSG00000101412',
 'ENSG00000101421',
 'ENSG00000101444',
 'ENSG00000101460',
 'ENSG00000101473',
 'ENSG00000101493',
 'ENSG00000101558',
 'ENSG00000101577',
 'ENSG00000101608',
 'ENSG00000101665',
 'ENSG00000101670',
 'ENSG00000101680',
 'ENSG00000101695',
 'ENSG00000101773',
 'ENSG00000101844',
 'ENSG00000101846',
 'ENSG00000101849',
 'ENSG00000101888',
 'ENSG00000101911',
 'ENSG00000101916',
 'ENSG00000101945',
 'ENSG00000101966',
 'ENSG00000101974',
 'ENSG00000102001',
 'ENSG00000102032',
 'ENSG00000102096',
 'ENSG00000102125',
 'ENSG00000102144',
 'ENSG00000102172',
 'ENSG00000102181',
 'ENSG00000102230',
 'ENSG00000102245',
 'ENSG00000102287',
 'ENSG00000102302',
 'ENSG00000102312',
 'ENSG00000102393',
 'ENSG00000102524',
 'ENSG00000102554',
 'ENSG00000102575',
 'ENSG00000102580',
 'ENSG00000102606',
 'ENSG00000102699',
 'ENSG00000102710',
 'ENSG00000102753',
 'ENSG00000102755',
 'ENSG00000102760',
 'ENSG00000102780',
 'ENSG00000102858',
 'ENSG00000102871',
 'ENSG00000102882',
 'ENSG00000102886',
 'ENSG00000102890',
 'ENSG00000102893',
 'ENSG00000102962',
 'ENSG00000102967',
 'ENSG00000102981',
 'ENSG00000102996',
 'ENSG00000103024',
 'ENSG00000103056',
 'ENSG00000103066',
 'ENSG00000103091',
 'ENSG00000103126',
 'ENSG00000103148',
 'ENSG00000103150',
 'ENSG00000103197',
 'ENSG00000103202',
 'ENSG00000103257',
 'ENSG00000103319',
 'ENSG00000103342',
 'ENSG00000103415',
 'ENSG00000103479',
 'ENSG00000103485',
 'ENSG00000103489',
 'ENSG00000103490',
 'ENSG00000103496',
 'ENSG00000103502',
 'ENSG00000103522',
 'ENSG00000103653',
 'ENSG00000103707',
 'ENSG00000103769',
 'ENSG00000103811',
 'ENSG00000103876',
 'ENSG00000103942',
 'ENSG00000104067',
 'ENSG00000104142',
 'ENSG00000104205',
 'ENSG00000104290',
 'ENSG00000104312',
 'ENSG00000104321',
 'ENSG00000104331',
 'ENSG00000104332',
 'ENSG00000104365',
 'ENSG00000104368',
 'ENSG00000104375',
 'ENSG00000104388',
 'ENSG00000104408',
 'ENSG00000104432',
 'ENSG00000104518',
 'ENSG00000104522',
 'ENSG00000104524',
 'ENSG00000104549',
 'ENSG00000104687',
 'ENSG00000104689',
 'ENSG00000104691',
 'ENSG00000104695',
 'ENSG00000104763',
 'ENSG00000104765',
 'ENSG00000104812',
 'ENSG00000104814',
 'ENSG00000104825',
 'ENSG00000104835',
 'ENSG00000104856',
 'ENSG00000104879',
 'ENSG00000104880',
 'ENSG00000104881',
 'ENSG00000104885',
 'ENSG00000104892',
 'ENSG00000104899',
 'ENSG00000104903',
 'ENSG00000104915',
 'ENSG00000104921',
 'ENSG00000104946',
 'ENSG00000104951',
 'ENSG00000104953',
 'ENSG00000104972',
 'ENSG00000104974',
 'ENSG00000104998',
 'ENSG00000105122',
 'ENSG00000105131',
 'ENSG00000105136',
 'ENSG00000105173',
 'ENSG00000105220',
 'ENSG00000105221',
 'ENSG00000105223',
 'ENSG00000105229',
 'ENSG00000105245',
 'ENSG00000105281',
 'ENSG00000105287',
 'ENSG00000105289',
 'ENSG00000105325',
 'ENSG00000105327',
 'ENSG00000105329',
 'ENSG00000105357',
 'ENSG00000105369',
 'ENSG00000105393',
 'ENSG00000105397',
 'ENSG00000105426',
 'ENSG00000105429',
 'ENSG00000105443',
 'ENSG00000105464',
 'ENSG00000105483',
 'ENSG00000105497',
 'ENSG00000105499',
 'ENSG00000105538',
 'ENSG00000105552',
 'ENSG00000105568',
 'ENSG00000105607',
 'ENSG00000105609',
 'ENSG00000105639',
 'ENSG00000105649',
 'ENSG00000105655',
 'ENSG00000105656',
 'ENSG00000105664',
 'ENSG00000105695',
 'ENSG00000105701',
 'ENSG00000105708',
 'ENSG00000105711',
 'ENSG00000105723',
 'ENSG00000105750',
 'ENSG00000105755',
 'ENSG00000105810',
 'ENSG00000105835',
 'ENSG00000105851',
 'ENSG00000105855',
 'ENSG00000105877',
 'ENSG00000105928',
 'ENSG00000105929',
 'ENSG00000105953',
 'ENSG00000105971',
 'ENSG00000105974',
 'ENSG00000105976',
 'ENSG00000105989',
 'ENSG00000106003',
 'ENSG00000106018',
 'ENSG00000106049',
 'ENSG00000106052',
 'ENSG00000106070',
 'ENSG00000106089',
 'ENSG00000106100',
 'ENSG00000106123',
 'ENSG00000106211',
 'ENSG00000106258',
 'ENSG00000106278',
 'ENSG00000106299',
 'ENSG00000106327',
 'ENSG00000106348',
 'ENSG00000106366',
 'ENSG00000106367',
 'ENSG00000106392',
 'ENSG00000106397',
 'ENSG00000106404',
 'ENSG00000106459',
 'ENSG00000106462',
 'ENSG00000106483',
 'ENSG00000106526',
 'ENSG00000106546',
 'ENSG00000106571',
 'ENSG00000106605',
 'ENSG00000106615',
 'ENSG00000106617',
 'ENSG00000106636',
 'ENSG00000106683',
 'ENSG00000106692',
 'ENSG00000106733',

In [48]:
brca.ensgv

                    ensgv             ensg      name
0      ENSG00000000003.15  ENSG00000000003    TSPAN6
1       ENSG00000000005.6  ENSG00000000005      TNMD
2      ENSG00000000419.13  ENSG00000000419      DPM1
3      ENSG00000000457.14  ENSG00000000457     SCYL3
4      ENSG00000000460.17  ENSG00000000460  C1orf112
...                   ...              ...       ...
60655   ENSG00000288669.1  ENSG00000288669       NaN
60656   ENSG00000288670.1  ENSG00000288670       NaN
60657   ENSG00000288671.1  ENSG00000288671       NaN
60658   ENSG00000288674.1  ENSG00000288674       NaN
60659   ENSG00000288675.1  ENSG00000288675       NaN

[60660 rows x 3 columns]

In [26]:
cortex.X

array([[0, 3, 3, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 0, 6, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]], shape=(3005, 19972), dtype=int32)

In [30]:
cortex.obs['labels'].unique()

array([2, 6, 5, 4, 3, 1, 0])

In [33]:
cortex.obs['precise_labels'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
cortex.obs['cell_type'].unique()

array(['interneurons', 'pyramidal SS', 'pyramidal CA1',
       'oligodendrocytes', 'microglia', 'endothelial-mural',
       'astrocytes_ependymal'], dtype=object)

In [60]:
cortex.var.index.to_series()

Tspan12              Tspan12
Tshz1                  Tshz1
Fnbp1l                Fnbp1l
Adamts15            Adamts15
Cldn12                Cldn12
                    ...
Gm20738_loc4    Gm20738_loc4
Gm20738_loc6    Gm20738_loc6
Gm21943_loc1    Gm21943_loc1
Gm21943_loc3    Gm21943_loc3
Gm20738_loc3    Gm20738_loc3
Length: 19972, dtype: object

In [21]:
name2ensg = pd.read_csv(dataset_dir/'other'/'name2ensg.csv')

In [23]:
names = list(cortex.var.index)
names

['Tspan12',
 'Tshz1',
 'Fnbp1l',
 'Adamts15',
 'Cldn12',
 'Rxfp1',
 '2310042E22Rik',
 'Sema3c',
 'Jam2',
 'Apbb1ip',
 'Frem2',
 'BC005764',
 'Deptor',
 'C130030K03Rik',
 'Klhl13',
 'Tnfaip8l3',
 'Ascl1',
 'Atp1b2',
 'Tmem132e',
 'Prkar2b',
 'Necab1',
 'Nr2f2',
 'Stmn1-rs1',
 'Shisa9',
 'Sub1',
 'Vat1l',
 'Pcdh18',
 'Dpysl5',
 'Agtr2',
 'Cxcl14',
 'Ptprf',
 'Cers5',
 'Nacc2',
 'Cntnap2',
 'Asic4',
 'Tph2',
 'Rit2',
 'Scg2',
 'Nr2e1',
 'Bmp3',
 'B3galnt1',
 'Gm9846',
 'Kcnn1',
 'Fam19a2',
 'Samd4',
 'Stmn1',
 'Egln3',
 'Bmper',
 'Cd200',
 '1810041L15Rik',
 'Rnf128',
 'P2ry1',
 'Sorcs1',
 'Htr3a',
 'Kcnip1',
 'Sco2',
 '2610044O15Rik8',
 'Tmem41b',
 'Cdh9',
 'Ppp2r3d',
 'Usp28',
 'Trib2',
 'L2hgdh',
 'Cited2',
 'Btbd11',
 'Rgs12',
 'Cnr1',
 'Kcnd3',
 'Htr3b',
 'Sulf2',
 'Capn5',
 'Osbpl5',
 'Nrtn',
 'Nr2f1',
 'Galnt14',
 'Slc35f1',
 'Mmgt1',
 'Htr7',
 'E130309F12Rik',
 'Wtap',
 'Racgap1',
 'Arhgap24',
 'Maml3',
 'Gng2',
 'Tnc',
 'Fndc3a',
 'Npas3',
 'Celf6',
 'Inpp4b',
 'Npas1',
 'Ache',
 'Clnk',
 'Sel1l3',
 'Adarb2',
 'Nrxn3',
 'Fam211b',
 'Akap7',
 'Chrna4',
 'Ugp2',
 'Tmem242',
 'Csdc2',
 'Camk2d',
 'Rph3a',
 'Olfm2',
 'Pcp4l1',
 'Ablim1',
 'Igf1',
 'Sorcs2',
 'Ddah1',
 '3110043O21Rik',
 'Adra1b',
 'Vash2',
 '2510009E07Rik',
 'Zfp518b',
 'Magi3',
 'Capza1',
 'Enho',
 'Asic1',
 'Gng4',
 'Bend4',
 'Stat5b',
 'Cntn4',
 'Slc35f4',
 'Frmd7',
 'Pdzd2',
 'Erbb4',
 'Bglap2',
 'Tac2',
 'Rpl34-ps1',
 'Fam163a',
 'Gm11110',
 'Hcn3',
 'Cenpa',
 'Col6a3',
 'Dlx6os1',
 'Col15a1',
 'Cacng5',
 'Xist',
 'Scn7a',
 'Dennd2a',
 'Wnt5a',
 'Tmem229b',
 'Cbln2',
 'Bloc1s3',
 'Socs2',
 'Slc18a3',
 'Mybpc1',
 'AI848285',
 'Wnt5b',
 'Tcerg1l',
 'Scgn',
 'Myl1',
 'Chat',
 'Gpr176',
 'Gpr68',
 'Hcrtr2',
 'Cntn6',
 'Col24a1',
 'Glra2',
 'Rgs16',
 'Scn5a',
 'Grpr',
 'Penk',
 'Calb2',
 'Rgs8',
 'Slc5a6',
 'Vangl2',
 'A230072E10Rik',
 'Bard1',
 'Lca5l',
 'H2-M5',
 'Bag2',
 'Trpc3',
 'Fam159b',
 'Gpc3',
 'Clrn1',
 'Dnajc4',
 'Rimklb',
 '2610002M06Rik',
 'Cep120',
 'Dfna5',
 'Dlx1',
 'Panx1',
 'Slc7a1',
 'Dlx2',
 'Acpl2',
 'Pag1',
 'Syngr3',
 'Rbms3',
 'Pgap1',
 'Dzank1',
 'Dcx',
 'Nap1l5',
 'Dbndd1',
 'Lancl3',
 'Peg3',
 'Rimkla',
 '1500011B03Rik',
 'Tbc1d8',
 'Dnm3',
 'Prpsap1',
 'Neto1',
 'Syt13',
 'Marcks',
 'Lhfpl3',
 'Nap1l3',
 'Tmsb10',
 'Fgf12',
 'Pitpnc1',
 'Hsdl1',
 'Iglon5',
 'Kcnh2',
 'Thsd7a',
 'Arhgdig',
 'Slc25a33',
 'AI504432',
 'Rpp25',
 'Rassf5',
 'Tmem130',
 'Slc8a3',
 'Whrn',
 'Cib2',
 'Sfrp2',
 'Tgoln1',
 'Rcan3',
 'Cdh7',
 'Camk2n2',
 'Ccne1',
 'Ppme1',
 'Polr3d',
 'Ugdh',
 'Glce',
 'Klhl29',
 'Mettl25',
 'Mrto4',
 'Sncb',
 'Tmem178',
 'Tfap4',
 'Dnajb9',
 'Zfp385a',
 'AF529169',
 'Fam161b',
 'Foxred2',
 'Wdr37',
 'Ppp1r3f',
 'Nploc4',
 'Mpp3',
 'Dlc1',
 'Ino80e',
 'Smim19',
 'Tbc1d24',
 'Serp2',
 'Dexi',
 'Samd10',
 'Ppfia4',
 'Fnta',
 'Rab11fip5',
 'Camk1',
 'Snx8',
 'Pelo',
 'Pitpnm3',
 'Ttn',
 'B3galt6',
 'Afg3l2',
 'Hibadh',
 'Dnm1l',
 'Gpr83',
 'Uqcc1',
 'Cdv3',
 'Egfr',
 'Esrrg',
 'Pank1',
 'Polr2m',
 '9630033F20Rik',
 'Adrbk2',
 'Syne1_loc2',
 'Ctnna2',
 'Arl5a',
 'Gjd2',
 'Pebp1',
 'Adc',
 'Cxx1b',
 'Gnal',
 'Cdc27',
 'Arhgef10l',
 'Nr1d2',
 'Elavl4',
 'Cntnap1',
 'Cops7a',
 'Tmem184b',
 'Cerk',
 'Map1lc3a',
 'Elof1',
 'Pitpna',
 'Faim2',
 'Slc45a1',
 'Kcnc1',
 'Maneal',
 'Psmb4',
 'B4galt5',
 'Impad1',
 'Myo5a',
 'Nipal3',
 'Mafb',
 'Dynll2',
 'Gnas',
 'Ctsd',
 'Gng3',
 'Slc38a1',
 'Kif1a',
 'Pgam1',
 'Tcf25',
 'Stxbp1',
 'Rims2',
 'Scn1a',
 'Efhd2',
 'Lgmn',
 'Vamp1',
 'Stox2',
 'Rnf11',
 'Plcb4',
 'Tspyl4',
 'Lynx1',
 'Capns1',
 'Ttyh3',
 'Vegfb',
 'Tiam1',
 'Bcap29',
 'Haus4',
 'Cxx1c',
 'Slc32a1',
 'Gas6',
 'Prkar1b',
 'Scoc',
 'Ell2',
 'Adam9',
 'Pdxk',
 'Nat8l',
 'Dnajb1',
 'Syngr1',
 'Bex2',
 'Aldoa',
 'Elavl2',
 'Cand1',
 'Orc5',
 'Srrm4',
 'Rnf217',
 'Dlx1os',
 'Atp6v0d1',
 'Pkm',
 'Pacsin2',
 'Rab5b',
 'Cdr1',
 'Dleu7',
 'Rufy3',
 'Sult4a1',
 'Phyhipl',
 'Aldh5a1',
 'Slc1a4',
 'Kbtbd2',
 'Etl4',
 'Cpeb3',
 'Shroom2',
 'Gapdh',
 'Adarb1',
 'Atp6v1b2',
 'Fundc1',
 'Rangap1',
 'LOC106740',
 'Rcan2',
 'Mllt11',
 'Rap1gds1',
 'Zc4h2',
 'Cplx1',
 'Kcna6',
 'Arnt2',
 'AA465934',
 'Vdac1',
 'Slc25a3',
 'Abat',
 'Lrrc3b',
 'Rpl3',
 'Kcna2',
 'Pclo',
 'Ankib1',
 'Hspa8',
 'Lpgat1',
 'Adcyap1r1',
 'Cltb',
 'Hdgfrp3',
 'Fam102b',
 'Hccs',
 'Vwc2',
 'Lrtm2',
 'Asic2',
 'Tbc1d9',
 'Klc1',
 'Lpin1',
 'Ndn',
 'Rpl41',
 'Ids',
 'Sfxn1',
 'Dnlz',
 'Fam63b',
 'Neto2',
 'Grip1',
 'Abhd8',
 'Ctps',
 'Ntrk2',
 'Cspg5',
 'Syt1',
 'Msi2',
 'Gm13363',
 'Gabarapl1',
 'Eef1a2',
 'Uba1',
 'Fam163b',
 'Mvb12b',
 'Got2',
 'Scg3',
 'Ipo4',
 'Ndrg4',
 'Srcin1',
 'Armcx2',
 'Lbh',
 'Smyd2',
 'Uggt1',
 'Ppip5k2',
 'Sv2a',
 'Wbp2',
 'Stau2',
 'Rab3a',
 'Clip3',
 'Smap1',
 'Atcay',
 'Prune2',
 'Polr3h',
 'Zfp941',
 'Impact',
 'Pcsk1n',
 'Pdxp',
 'Rasgrf2',
 'Bcat1',
 'Celf4',
 'Slc6a17',
 'Nova1',
 'Gnb1',
 'Cend1',
 'Pten',
 'Gm6682',
 'Cep170b',
 'Hdac6',
 'Syp',
 'Fam3c',
 'Steap2',
 'Pink1',
 'Apba1',
 'Fam149a',
 'Atp6v0e2',
 'Rnf14',
 'Oxct1',
 'Cxxc4',
 'Rps26',
 'Mcm6',
 'Atp6v0c-ps2',
 'Vamp2',
 'Slc2a3',
 'Ppm1h',
 'Rcn2',
 'Nipal2',
 'Bex1',
 'Ide',
 'Impdh1',
 'Alg2',
 'Sorbs1',
 'Grb10',
 'Rab6b',
 'Rusc1',
 'Aktip',
 'Gdap1',
 'Uri1',
 'Fbxo9',
 'Capn2',
 'Slc25a46',
 'Fam168b',
 'Glud1',
 '2900056M20Rik',
 'Tceal5',
 'Mbtps2',
 'Purb',
 'Trove2',
 'Sipa1l2',
 'Reep5',
 'Bcar1',
 'Clstn3',
 'Rtca',
 'Azin1',
 'Slc23a2',
 'Atp6v1a',
 'Pcgf2',
 'Ywhag',
 'Elovl4',
 'Snx15',
 'Mepce',
 'Rnd3',
 'Eif2s3x',
 'Eif4g2',
 'Ube2e1',
 'Tmem55b',
 'Gria4',
 'Scai',
 'Rps27a',
 'Ubc',
 'Sgpp1',
 'Rnf187',
 'Slc45a4',
 'Snurf',
 'Chst10',
 'Mfn2',
 'Thbs2',
 'Peg13',
 'Sqstm1',
 'Usp32',
 'Setd7',
 'Ankrd50',
 'Map3k9',
 'Cltc',
 'Snx16',
 'Epb4.1l1',
 'A330050F15Rik',
 'Osbpl3',
 'Csk',
 'Rab21',
 'Rps6ka6',
 'Chchd10',
 'Col26a1',
 'Auh',
 'Gnl3l',
 'Clasrp',
 'Xpr1',
 'Zfp811',
 'Dirc2',
 'Cacnb4',
 'Kcnab3',
 'Anxa7',
 'Coprs',
 'Igsf3',
 'Gm20300',
 'Uba6',
 'Abcd2',
 'Rgs17',
 'Tnfaip1',
 'Abcb7',
 'Tet1',
 'Tspan3',
 'Usp22',
 'Hipk1',
 'Fam73a',
 'Maf',
 'Ndufaf6',
 'Cacng2',
 'Btbd1',
 'Hivep1',
 'Magi1',
 'Acly',
 'Aplp2',
 'Tsc22d3',
 'Bend6',
 'Crlf2',
 'Tmem238',
 'Arl4c',
 'Cul4b',
 'Dlat',
 'Zfp385b',
 'Flywch2',
 'Mgll',
 '2310057M21Rik',
 'Scrt1',
 'Trnp1',
 'Rmnd5a',
 '2010107G23Rik',
 'Lars2',
 'Fbxo28',
 'Nrip3',
 'Efr3b',
 'Aldoart1',
 'Dmap1',
 'Slc2a13',
 'Gpr162',
 'Tmem56',
 'Ubash3b',
 '2310003H01Rik',
 'Ttc39b',
 'Ap2a1',
 'Kcnq5',
 'Rpl9',
 'Tfcp2',
 'Dhrs11',
 'Col14a1',
 'Sp8',
 'Cxcl5',
 'Rgs10',
 'Myh8',
 'Pnoc',
 'Snx7',
 'Znhit1',
 'Olfr920',
 'Baiap2l2',
 'Hhat',
 'Vwa5a',
 'Cpne4',
 'Cidea',
 'Gm5607',
 'Mrgpre',
 'Unc5d',
 'Trh',
 'Slc35d3',
 'Ptchd4',
 'Kcnc4',
 'Mtss1',
 'Sae1',
 'Sox1',
 'Gipc2',
 'Gal',
 'Lrp8',
 'Mcf2',
 'Diras1',
 'Ppp1r2',
 'Gm14204',
 'Tox3',
 'Alk',
 'Fam46a',
 'Pvrl2',
 'Grem2',
 'Fam98a',
 'Tex9',
 'Fmo1',
 'Mpdz',
 'Asph',
 'Lrrc4',
 'Zfp9',
 'Tbc1d30',
 'Atat1',
 'Vps33a',
 'Sv2c',
 'Lats2',
 'Sema5a',
 'Ptchd2',
 'Kcns3',
 'Crispld1',
 'Zfp362',
 'Tnnt1',
 'Cyb561',
 'Sp9',
 'Pknox2',
 'Atf5',
 'Ppat',
 'Arhgef6',
 'Prr24',
 'Slc6a1',
 'Rora',
 'Gpcpd1',
 'Gpr158',
 'Cadps',
 'Lrrtm3',
 'Rnf38',
 'Rgmb',
 'Nmbr',
 'Afap1',
 'Rnf207',
 'Pigu',
 'Ttbk2',
 'Srgap1',
 'Atg9b',
 'Zc3h12c',
 '6030419C18Rik',
 'Cntn5',
 'Mycn',
 'Tmem25',
 'Cenpp',
 'Fgf9',
 'Ptprm',
 'Pld5',
 'Ogfrl1',
 'Hrh3',
 'Arx',
 'Klf12',
 'Hapln1',
 'Sp4',
 'Gad1',
 'Osbpl8',
 'Dnajc6',
 'Trpc7',
 'Nacad',
 'Lgr5',
 'Sun2',
 'Slc35e3',
 'Gde1',
 'Grip2',
 'Epb4.1l5',
 'Mctp1',
 '6430548M08Rik',
 'Cyp2s1',
 'Rbms1',
 'Frmpd4',
 'Lmo2',
 'Irs1',
 'Klhdc8b',
 'Gad2',
 'Lgi2',
 'Plcxd2',
 'Tmsb15b2',
 'Nrsn1',
 'B930025P03Rik',
 'Dner',
 'Garnl3',
 'Nmnat2',
 'A830018L16Rik',
 'Prps2',
 'Chml',
 'Cks1b',
 'Trim66',
 'Cgn',
 'Tmem65',
 'Tmem151b',
 'Lrp12',
 'Grsf1',
 'Prkaa2',
 'Slc39a6',
 'Gabrb2',
 'Tspan7',
 'Lrrtm2',
 'Gabra1',
 'Prune',
 'Rnf152',
 'Adra1a',
 'Zmat4',
 'Mapk8',
 'Sgk1',
 'Slc30a4',
 'Dock3',
 'Grik1',
 'Gpr12',
 'Spock3',
 'Mkrn3',
 'Ndnf',
 'Ssbp2',
 'Pogk',
 'Reln',
 'Spock1',
 'Ptprt',
 'Ntn1',
 'Vcan',
 'Th',
 'Ecel1',
 'Tekt5',
 'Slc5a7',
 'Npy',
 'Tacr1',
 'Chodl',
 '2010001M06Rik',
 'Gpr126',
 'Emb',
 'Resp18',
 'Crhbp',
 'Stard5',
 'Cort',
 'Zfp954',
 'Hist1h2ap_loc1',
 'Unc13c',
 'Slc5a5',
 'Lrpap1',
 'Sst',
 'Rbp4',
 'Lypd6',
 'Rab3b',
 'Tsix',
 'Dnajc28',
 'Zwint',
 'Fuom',
 'Cryl1',
 'Kcnmb2',
 'Oprk1',
 'Ankrd34b',
 'Stmn3',
 'Nek7',
 'Ndufa4',
 'Stac2',
 'Cacna2d2',
 'Ifit2',
 'Kcnc2',
 'Klhdc9',
 'Bfsp1',
 'Tac1',
 'Stk32a',
 'Lrrc38',
 'Gna14',
 'Akr1c18',
 'Relt',
 'Gm4980',
 'Mme',
 'I830012O16Rik',
 'Mkx',
 'Zfp558',
 'Nxph1',
 'A030009H04Rik',
 'Nap1l2',
 'Cdh13',
 'Nppc',
 'AI413582',
 'Olfm3',
 'Rxfp3',
 'Trpc6',
 'Elfn1',
 'Pappa',
 'LOC100861615',
 'Lhx6',
 'Kctd8',
 'Mstn',
 'Lypd6b',
 'AW551984',
 'Tmem132c',
 'Sla',
 'Sox6',
 'Mrap2',
 'Nxph2',
 'Moxd1',
 'Timm8a1',
 'Pvalb',
 'Snora30',
 'Tuba8',
 'Gadd45g',
 'Inadl_loc1',
 'Klhl14',
 'Gys2',
 '4930426D05Rik',
 'Wnt7a',
 'B230216G23Rik',
 'Gm5868',
 'Cpne5',
 'Rarres1',
 'Slc10a4',
 'Cntnap3',
 'Tmem91',
 'Crabp1',
 'Neb',
 'Zfp442',
 'Htr2c',
 'Ppil1',
 'Tamm41',
 'Slc7a3',
 'Cenph',
 'Ap1s2',
 'Pnck',
 'Hmgn2',
 'Serpini1',
 'C1ql1',
 'Dusp26',
 'Gm14436',
 'Rps4y2',
 'Selm',
 'Stk32b',
 'Gtpbp8',
 '1110038B12Rik',
 'G0s2',
 'Akr1e1',
 'Sumo1',
 'Rwdd3',
 'Smim18',
 'Rpl7',
 'Bex4',
 'Bnip3',
 'Gm14305',
 'Pcbd1',
 'OTTMUSG00000016609_loc4',
 'Glrx',
 'Pafah1b3',
 'Synpr',
 'Lnx1',
 'Qpct',
 'OTTMUSG00000016609_loc3',
 'Dynlrb1',
 'Zcchc12',
 'Ndufv3',
 'Ccdc28a',
 'Cdk5rap1',
 'Ggact',
 'Gstm5',
 'Acadm',
 'Fxyd6',
 'Prmt2',
 'Prpf38a',
 'Commd6',
 'Hnmt',
 '2900011O08Rik',
 'Snx6',
 'Psmd10',
 'Tmem41a',
 'Gm15421',
 'Mospd1',
 'Ndufa5',
 'Cox7b',
 'Zfp931',
 'Rnasek',
 'Cacybp',
 'Uqcrh',
 'Hcfc1r1',
 'Tmsb15l',
 '1110032A03Rik',
 'Sms',
 'Ndufb10',
 'Araf',
 'Eif4a2',
 'Ndufa8',
 'Atp5j2',
 'Tango2',
 '1700037H04Rik',
 'Ndufab1',
 'Ldhb',
 'Atp5f1',
 'Ndufa13',
 'Uqcrc2',
 'Ndufv2',
 'Hprt',
 'Atp5j',
 'Ddt',
 'Fkbp3',
 'Ndufa11',
 'Ndufa6',
 'Atp6v1f',
 'Ndufb9',
 'Pml',
 'Smim4',
 'Gm5643_loc2',
 'Ngfrap1',
 'Wbp5',
 'Nop10',
 'Akr1a1',
 'Mdh1',
 'Vdac3',
 'Mxra7',
 'Tspan6',
 'BC002163_loc2',
 'Otub1',
 'Sod1',
 'Hars',
 'BC002163_loc1',
 'Psmb5',
 'Ndufb5',
 'Hspe1',
 'Gpx4',
 'Cox4i1',
 'Sncg',
 'Pagr1a',
 'Npm1',
 'Ndufb6',
 'Myl12b',
 'Idh3b',
 'Hint1',
 'Gpi1',
 'Atp6v1e1',
 'Cct8',
 'Uchl1',
 'Mtfr1l',
 'Pts',
 'Sucla2',
 'Tmx2',
 'Fabp3',
 'Atp5h',
 'Rnd2',
 'Gm14326',
 'Pdhb',
 'Ppa1',
 'Gm5506_loc1',
 'Gabarapl2',
 'Atp5g3',
 'Acot7',
 'Pdha1',
 'Got1',
 'Tuba1b',
 'Slc25a4',
 '2700097O09Rik',
 'Haus8',
 'Pkib',
 'S100a10',
 'Chchd2',
 'Asns',
 'Idh3a',
 'Atp5b',
 'Prdx2',
 'Nudt19',
 'Ckb',
 'Morf4l2',
 'Tubb2a',
 'Pja1',
 'Tuba1a',
 'Stmn2',
 '5330434G04Rik',
 'Vipas39',
 'Ndfip1',
 ...]

In [22]:
name2ensg

                  ensg     name
0      ENSG00000004059     ARF5
1      ENSG00000003056     M6PR
2      ENSG00000004478    FKBP4
3      ENSG00000003137  CYP26B1
4      ENSG00000003509  NDUFAF7
...                ...      ...
19380  ENSG00000132746  ALDH3B2
19381  ENSG00000196990  FAM163B
19382  ENSG00000188039     NWD1
19383  ENSG00000198728     LDB1
19384  ENSG00000181827     RFX7

[19385 rows x 2 columns]

In [55]:
name2ensg

                  ensg     name
0      ENSG00000004059     ARF5
1      ENSG00000003056     M6PR
2      ENSG00000004478    FKBP4
3      ENSG00000003137  CYP26B1
4      ENSG00000003509  NDUFAF7
...                ...      ...
19380  ENSG00000132746  ALDH3B2
19381  ENSG00000196990  FAM163B
19382  ENSG00000188039     NWD1
19383  ENSG00000198728     LDB1
19384  ENSG00000181827     RFX7

[19385 rows x 2 columns]

In [15]:
kegg.relation

,set_idx,node_i_idx,node_j_idx,activation,binding/association,compound,dephosphorylation,dissociation,expression,glycosylation,indirect,indirect effect,inhibition,methylation,missing interaction,phosphorylation,repression,state change,ubiquitination
0,0,4131.0,314.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
1,0,4131.0,2201.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
2,0,4131.0,2821.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,0,3178.0,314.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
4,0,3178.0,2201.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75934,304,2013.0,3586.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
75935,304,2013.0,1028.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
75936,304,4266.0,2105.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
75937,304,4266.0,3586.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
75938,304,4266.0,1028.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [67]:
import numpy as np
import pandas as pd
from typing import Iterable, Optional, Tuple

def filter_genes_by_ensg(
    X: np.ndarray,
    names: pd.Index,
    name2ensg: pd.DataFrame,
    ensg_filter: Optional[Iterable[str]] = None,
) -> Tuple[np.ndarray, pd.Index, pd.Series]:
    """
    Filter genes based on name↔ENSG mapping (case-insensitive), with optional ENSG filtering.

    Returns
    -------
    X_filt : np.ndarray
        Filtered expression matrix, shape (samples, kept_genes)
    names_filt : pd.Index
        Filtered gene names (original casing preserved)
    ensg_filt : pd.Series
        ENSG IDs aligned to names_filt
    """

    # --- normalize case ---
    names_lc = names.str.lower()

    n2e = name2ensg.copy()
    n2e["name_lc"] = n2e["name"].str.lower()

    # --- optional ENSG restriction ---
    if ensg_filter is not None:
        ensg_filter = set(map(str, ensg_filter))
        n2e = n2e[n2e["ensg"].isin(ensg_filter)]

    # --- build name → ENSG mapping ---
    name_to_ensg = (
        n2e
        .drop_duplicates("name_lc")
        .set_index("name_lc")["ensg"]
    )

    # --- find valid genes ---
    mask = names_lc.isin(name_to_ensg.index)

    # --- apply filtering ---
    X_filt = X[:, mask]
    names_filt = names[mask]
    ensg_filt = names_lc[mask].map(name_to_ensg)

    return X_filt, names_filt, ensg_filt

In [76]:
kegg.ensg

['ENSG00000000938',
 'ENSG00000001084',
 'ENSG00000001167',
 'ENSG00000001617',
 'ENSG00000001626',
 'ENSG00000001630',
 'ENSG00000001631',
 'ENSG00000002330',
 'ENSG00000002549',
 'ENSG00000002726',
 'ENSG00000003056',
 'ENSG00000003137',
 'ENSG00000003393',
 'ENSG00000003400',
 'ENSG00000003402',
 'ENSG00000003987',
 'ENSG00000004139',
 'ENSG00000004455',
 'ENSG00000004468',
 'ENSG00000004487',
 'ENSG00000004660',
 'ENSG00000004779',
 'ENSG00000004799',
 'ENSG00000004897',
 'ENSG00000004961',
 'ENSG00000004975',
 'ENSG00000005007',
 'ENSG00000005022',
 'ENSG00000005100',
 'ENSG00000005187',
 'ENSG00000005249',
 'ENSG00000005339',
 'ENSG00000005483',
 'ENSG00000005801',
 'ENSG00000005844',
 'ENSG00000005882',
 'ENSG00000005884',
 'ENSG00000005893',
 'ENSG00000005961',
 'ENSG00000006062',
 'ENSG00000006071',
 'ENSG00000006125',
 'ENSG00000006210',
 'ENSG00000006283',
 'ENSG00000006327',
 'ENSG00000006432',
 'ENSG00000006451',
 'ENSG00000006530',
 'ENSG00000006534',
 'ENSG00000006607',
 'ENSG00000006625',
 'ENSG00000006638',
 'ENSG00000006695',
 'ENSG00000006715',
 'ENSG00000006747',
 'ENSG00000006757',
 'ENSG00000006831',
 'ENSG00000007168',
 'ENSG00000007174',
 'ENSG00000007264',
 'ENSG00000007312',
 'ENSG00000007384',
 'ENSG00000007402',
 'ENSG00000007866',
 'ENSG00000007908',
 'ENSG00000007933',
 'ENSG00000007944',
 'ENSG00000007952',
 'ENSG00000007968',
 'ENSG00000008018',
 'ENSG00000008130',
 'ENSG00000008256',
 'ENSG00000008311',
 'ENSG00000008394',
 'ENSG00000008513',
 'ENSG00000008516',
 'ENSG00000008735',
 'ENSG00000009724',
 'ENSG00000009830',
 'ENSG00000009844',
 'ENSG00000009950',
 'ENSG00000010256',
 'ENSG00000010310',
 'ENSG00000010319',
 'ENSG00000010327',
 'ENSG00000010404',
 'ENSG00000010539',
 'ENSG00000010610',
 'ENSG00000010671',
 'ENSG00000010704',
 'ENSG00000010810',
 'ENSG00000010932',
 'ENSG00000011009',
 'ENSG00000011028',
 'ENSG00000011198',
 'ENSG00000011405',
 'ENSG00000011422',
 'ENSG00000011465',
 'ENSG00000011485',
 'ENSG00000011566',
 'ENSG00000011600',
 'ENSG00000011677',
 'ENSG00000012048',
 'ENSG00000012124',
 'ENSG00000012171',
 'ENSG00000012211',
 'ENSG00000012232',
 'ENSG00000012660',
 'ENSG00000012779',
 'ENSG00000013016',
 'ENSG00000013297',
 'ENSG00000013375',
 'ENSG00000013725',
 'ENSG00000014216',
 'ENSG00000014919',
 'ENSG00000015285',
 'ENSG00000015475',
 'ENSG00000015532',
 'ENSG00000016391',
 'ENSG00000017427',
 'ENSG00000017797',
 'ENSG00000018236',
 'ENSG00000018408',
 'ENSG00000018625',
 'ENSG00000018869',
 'ENSG00000019186',
 'ENSG00000019549',
 'ENSG00000019582',
 'ENSG00000019991',
 'ENSG00000020633',
 'ENSG00000020922',
 'ENSG00000021645',
 'ENSG00000021762',
 'ENSG00000021826',
 'ENSG00000023228',
 'ENSG00000023287',
 'ENSG00000023330',
 'ENSG00000023445',
 'ENSG00000023697',
 'ENSG00000023909',
 'ENSG00000025039',
 'ENSG00000025423',
 'ENSG00000025434',
 'ENSG00000025708',
 'ENSG00000026025',
 'ENSG00000026103',
 'ENSG00000026508',
 'ENSG00000026652',
 'ENSG00000027075',
 'ENSG00000027697',
 'ENSG00000027847',
 'ENSG00000027869',
 'ENSG00000028137',
 'ENSG00000028277',
 'ENSG00000028839',
 'ENSG00000029534',
 'ENSG00000030110',
 'ENSG00000031698',
 'ENSG00000032444',
 'ENSG00000033011',
 'ENSG00000033050',
 'ENSG00000033100',
 'ENSG00000033170',
 'ENSG00000033327',
 'ENSG00000033627',
 'ENSG00000033800',
 'ENSG00000034152',
 'ENSG00000034713',
 'ENSG00000035403',
 'ENSG00000035664',
 'ENSG00000035681',
 'ENSG00000035687',
 'ENSG00000036257',
 'ENSG00000036530',
 'ENSG00000037280',
 'ENSG00000037757',
 'ENSG00000038210',
 'ENSG00000038274',
 'ENSG00000039068',
 'ENSG00000039139',
 'ENSG00000039319',
 'ENSG00000039537',
 'ENSG00000040199',
 'ENSG00000040933',
 'ENSG00000041357',
 'ENSG00000041880',
 'ENSG00000041982',
 'ENSG00000042286',
 'ENSG00000042445',
 'ENSG00000042753',
 'ENSG00000043462',
 'ENSG00000043591',
 'ENSG00000044115',
 'ENSG00000044446',
 'ENSG00000044524',
 'ENSG00000044574',
 'ENSG00000046604',
 'ENSG00000047230',
 'ENSG00000047249',
 'ENSG00000047410',
 'ENSG00000047457',
 'ENSG00000048392',
 'ENSG00000048462',
 'ENSG00000049089',
 'ENSG00000049130',
 'ENSG00000049239',
 'ENSG00000049246',
 'ENSG00000049249',
 'ENSG00000049323',
 'ENSG00000049618',
 'ENSG00000049759',
 'ENSG00000049768',
 'ENSG00000049769',
 'ENSG00000049860',
 'ENSG00000050555',
 'ENSG00000050628',
 'ENSG00000050748',
 'ENSG00000050820',
 'ENSG00000051128',
 'ENSG00000051180',
 'ENSG00000051382',
 'ENSG00000051523',
 'ENSG00000052723',
 'ENSG00000052795',
 'ENSG00000052802',
 'ENSG00000053747',
 'ENSG00000053900',
 'ENSG00000053918',
 'ENSG00000054179',
 'ENSG00000054983',
 'ENSG00000055130',
 'ENSG00000055208',
 'ENSG00000055332',
 'ENSG00000055609',
 'ENSG00000055917',
 'ENSG00000056558',
 'ENSG00000056736',
 'ENSG00000056972',
 'ENSG00000056998',
 'ENSG00000057252',
 'ENSG00000057663',
 'ENSG00000058063',
 'ENSG00000058085',
 'ENSG00000058272',
 'ENSG00000058335',
 'ENSG00000058404',
 'ENSG00000058668',
 'ENSG00000058866',
 'ENSG00000059377',
 'ENSG00000059573',
 'ENSG00000059691',
 'ENSG00000060138',
 'ENSG00000060237',
 'ENSG00000060558',
 'ENSG00000060642',
 'ENSG00000060971',
 'ENSG00000060982',
 'ENSG00000061455',
 'ENSG00000061918',
 'ENSG00000062038',
 'ENSG00000062282',
 'ENSG00000062370',
 'ENSG00000062485',
 'ENSG00000062598',
 'ENSG00000062716',
 'ENSG00000063046',
 'ENSG00000063176',
 'ENSG00000063587',
 'ENSG00000063601',
 'ENSG00000063660',
 'ENSG00000063854',
 'ENSG00000064012',
 'ENSG00000064225',
 'ENSG00000064300',
 'ENSG00000064309',
 'ENSG00000064393',
 'ENSG00000064419',
 'ENSG00000064490',
 'ENSG00000064547',
 'ENSG00000064601',
 'ENSG00000064651',
 'ENSG00000064692',
 'ENSG00000064989',
 'ENSG00000065029',
 'ENSG00000065135',
 'ENSG00000065154',
 'ENSG00000065243',
 'ENSG00000065357',
 'ENSG00000065361',
 'ENSG00000065518',
 'ENSG00000065526',
 'ENSG00000065534',
 'ENSG00000065559',
 'ENSG00000065613',
 'ENSG00000065621',
 'ENSG00000065675',
 'ENSG00000065717',
 'ENSG00000065833',
 'ENSG00000065882',
 'ENSG00000065911',
 'ENSG00000065989',
 'ENSG00000066027',
 'ENSG00000066044',
 'ENSG00000066117',
 'ENSG00000066136',
 'ENSG00000066248',
 'ENSG00000066322',
 'ENSG00000066336',
 'ENSG00000066427',
 'ENSG00000066468',
 'ENSG00000066739',
 'ENSG00000066926',
 'ENSG00000067057',
 'ENSG00000067064',
 'ENSG00000067113',
 'ENSG00000067141',
 'ENSG00000067177',
 'ENSG00000067182',
 'ENSG00000067191',
 'ENSG00000067225',
 'ENSG00000067369',
 'ENSG00000067560',
 'ENSG00000067606',
 'ENSG00000067829',
 'ENSG00000067900',
 'ENSG00000067992',
 'ENSG00000068001',
 'ENSG00000068024',
 'ENSG00000068028',
 'ENSG00000068078',
 'ENSG00000068120',
 'ENSG00000068305',
 'ENSG00000068308',
 'ENSG00000068323',
 'ENSG00000068366',
 'ENSG00000068383',
 'ENSG00000068650',
 'ENSG00000068745',
 'ENSG00000068831',
 'ENSG00000068903',
 'ENSG00000068971',
 'ENSG00000068976',
 'ENSG00000069399',
 'ENSG00000069509',
 'ENSG00000069535',
 'ENSG00000069667',
 'ENSG00000069849',
 'ENSG00000069869',
 'ENSG00000069943',
 'ENSG00000069956',
 'ENSG00000069966',
 'ENSG00000070010',
 'ENSG00000070018',
 'ENSG00000070087',
 'ENSG00000070190',
 'ENSG00000070193',
 'ENSG00000070214',
 'ENSG00000070366',
 'ENSG00000070371',
 'ENSG00000070501',
 'ENSG00000070526',
 'ENSG00000070540',
 'ENSG00000070610',
 'ENSG00000070731',
 'ENSG00000070756',
 'ENSG00000070770',
 'ENSG00000070831',
 'ENSG00000070886',
 'ENSG00000070961',
 'ENSG00000071051',
 'ENSG00000071054',
 'ENSG00000071073',
 'ENSG00000071205',
 'ENSG00000071242',
 'ENSG00000071553',
 'ENSG00000071564',
 'ENSG00000071626',
 'ENSG00000072042',
 'ENSG00000072062',
 'ENSG00000072110',
 'ENSG00000072133',
 'ENSG00000072210',
 'ENSG00000072274',
 'ENSG00000072310',
 'ENSG00000072364',
 'ENSG00000072415',
 'ENSG00000072506',
 'ENSG00000072682',
 'ENSG00000072694',
 'ENSG00000072736',
 'ENSG00000072778',
 'ENSG00000072803',
 'ENSG00000072840',
 'ENSG00000072952',
 'ENSG00000072958',
 'ENSG00000073008',
 'ENSG00000073350',
 'ENSG00000073417',
 'ENSG00000073578',
 'ENSG00000073584',
 'ENSG00000073711',
 'ENSG00000073737',
 'ENSG00000073756',
 'ENSG00000073803',
 'ENSG00000073849',
 'ENSG00000073861',
 'ENSG00000073969',
 'ENSG00000074047',
 'ENSG00000074181',
 'ENSG00000074211',
 'ENSG00000074219',
 'ENSG00000074319',
 'ENSG00000074370',
 'ENSG00000074416',
 'ENSG00000074660',
 'ENSG00000074696',
 'ENSG00000074800',
 'ENSG00000075073',
 'ENSG00000075213',
 'ENSG00000075218',
 'ENSG00000075223',
 'ENSG00000075239',
 'ENSG00000075388',
 'ENSG00000075391',
 'ENSG00000075407',
 'ENSG00000075426',
 'ENSG00000075461',
 'ENSG00000075624',
 'ENSG00000075643',
 'ENSG00000075651',
 'ENSG00000075711',
 'ENSG00000075785',
 'ENSG00000075826',
 'ENSG00000075886',
 'ENSG00000076258',
 'ENSG00000076356',
 'ENSG00000076555',
 'ENSG00000076604',
 'ENSG00000076685',
 'ENSG00000076716',
 'ENSG00000076864',
 'ENSG00000076928',
 'ENSG00000076984',
 'ENSG00000077044',
 'ENSG00000077150',
 'ENSG00000077157',
 'ENSG00000077238',
 'ENSG00000077264',
 'ENSG00000077420',
 'ENSG00000077463',
 'ENSG00000077782',
 'ENSG00000077943',
 'ENSG00000078061',
 'ENSG00000078070',
 'ENSG00000078124',
 'ENSG00000078142',
 'ENSG00000078237',
 'ENSG00000078269',
 'ENSG00000078295',
 'ENSG00000078304',
 'ENSG00000078369',
 'ENSG00000078401',
 'ENSG00000078549',
 'ENSG00000078668',
 'ENSG00000078747',
 'ENSG00000078804',
 'ENSG00000078900',
 'ENSG00000079102',
 'ENSG00000079277',
 'ENSG00000079332',
 'ENSG00000079337',
 'ENSG00000079435',
 'ENSG00000079459',
 'ENSG00000079462',
 'ENSG00000079739',
 'ENSG00000079805',
 'ENSG00000079841',
 'ENSG00000079950',
 'ENSG00000079999',
 'ENSG00000080503',
 'ENSG00000080546',
 'ENSG00000080815',
 'ENSG00000080819',
 'ENSG00000080824',
 'ENSG00000080839',
 'ENSG00000081026',
 'ENSG00000081041',
 'ENSG00000081051',
 'ENSG00000081052',
 'ENSG00000081059',
 'ENSG00000081181',
 'ENSG00000081189',
 'ENSG00000081237',
 'ENSG00000081248',
 'ENSG00000081386',
 'ENSG00000081479',
 'ENSG00000081665',
 'ENSG00000081760',
 'ENSG00000081913',
 'ENSG00000081985',
 'ENSG00000082014',
 'ENSG00000082175',
 'ENSG00000082212',
 'ENSG00000082258',
 'ENSG00000082458',
 'ENSG00000082482',
 'ENSG00000082512',
 'ENSG00000082701',
 'ENSG00000082781',
 'ENSG00000082898',
 'ENSG00000083093',
 'ENSG00000083123',
 'ENSG00000083290',
 'ENSG00000083444',
 'ENSG00000083457',
 'ENSG00000083720',
 'ENSG00000083750',
 'ENSG00000083799',
 'ENSG00000083807',
 'ENSG00000083812',
 'ENSG00000083814',
 'ENSG00000083817',
 'ENSG00000083828',
 'ENSG00000083844',
 'ENSG00000083937',
 'ENSG00000084073',
 'ENSG00000084093',
 'ENSG00000084112',
 'ENSG00000084207',
 'ENSG00000084674',
 'ENSG00000084733',
 'ENSG00000084754',
 'ENSG00000084774',
 'ENSG00000085117',
 'ENSG00000085231',
 'ENSG00000085276',
 'ENSG00000085377',
 'ENSG00000085415',
 'ENSG00000085511',
 'ENSG00000085514',
 'ENSG00000085662',
 'ENSG00000085733',
 'ENSG00000085741',
 'ENSG00000085871',
 'ENSG00000085978',
 'ENSG00000085998',
 'ENSG00000086062',
 'ENSG00000086065',
 'ENSG00000086102',
 'ENSG00000086205',
 'ENSG00000086232',
 'ENSG00000086475',
 'ENSG00000086544',
 'ENSG00000086619',
 'ENSG00000086696',
 'ENSG00000086730',
 'ENSG00000086758',
 'ENSG00000086848',
 'ENSG00000086991',
 'ENSG00000087008',
 'ENSG00000087053',
 'ENSG00000087074',
 'ENSG00000087077',
 'ENSG00000087085',
 'ENSG00000087086',
 'ENSG00000087088',
 'ENSG00000087095',
 'ENSG00000087157',
 'ENSG00000087237',
 'ENSG00000087245',
 'ENSG00000087253',
 'ENSG00000087258',
 'ENSG00000087266',
 'ENSG00000087460',
 'ENSG00000087470',
 'ENSG00000087494',
 'ENSG00000087586',
 'ENSG00000088002',
 'ENSG00000088035',
 'ENSG00000088256',
 'ENSG00000088280',
 'ENSG00000088305',
 'ENSG00000088766',
 'ENSG00000088826',
 'ENSG00000088827',
 'ENSG00000088833',
 'ENSG00000088876',
 'ENSG00000088888',
 'ENSG00000088899',
 'ENSG00000089012',
 'ENSG00000089022',
 'ENSG00000089053',
 'ENSG00000089127',
 'ENSG00000089159',
 'ENSG00000089163',
 'ENSG00000089234',
 'ENSG00000089248',
 'ENSG00000089289',
 'ENSG00000089335',
 'ENSG00000089472',
 'ENSG00000089597',
 'ENSG00000089685',
 'ENSG00000090013',
 'ENSG00000090020',
 'ENSG00000090054',
 'ENSG00000090266',
 'ENSG00000090339',
 'ENSG00000090376',
 'ENSG00000090432',
 'ENSG00000090447',
 'ENSG00000090539',
 'ENSG00000090612',
 'ENSG00000090621',
 'ENSG00000090659',
 'ENSG00000090661',
 'ENSG00000090776',
 'ENSG00000090863',
 'ENSG00000091073',
 'ENSG00000091106',
 'ENSG00000091129',
 'ENSG00000091136',
 'ENSG00000091140',
 'ENSG00000091409',
 'ENSG00000091428',
 'ENSG00000091436',
 'ENSG00000091483',
 'ENSG00000091513',
 'ENSG00000091592',
 'ENSG00000091831',
 'ENSG00000091879',
 'ENSG00000092010',
 'ENSG00000092020',
 'ENSG00000092054',
 'ENSG00000092439',
 'ENSG00000092445',
 'ENSG00000092621',
 'ENSG00000092758',
 'ENSG00000092820',
 'ENSG00000092841',
 'ENSG00000092964',
 'ENSG00000092969',
 'ENSG00000093010',
 'ENSG00000093072',
 'ENSG00000093144',
 'ENSG00000093217',
 'ENSG00000094755',
 'ENSG00000094804',
 'ENSG00000094880',
 'ENSG00000094963',
 'ENSG00000095015',
 'ENSG00000095203',
 'ENSG00000095303',
 'ENSG00000095380',
 'ENSG00000095539',
 'ENSG00000095585',
 'ENSG00000095637',
 'ENSG00000095739',
 'ENSG00000095794',
 'ENSG00000096063',
 'ENSG00000096384',
 'ENSG00000096433',
 'ENSG00000096654',
 'ENSG00000096717',
 'ENSG00000096968',
 'ENSG00000096996',
 'ENSG00000097007',
 'ENSG00000097021',
 'ENSG00000097033',
 'ENSG00000099194',
 'ENSG00000099204',
 'ENSG00000099250',
 'ENSG00000099365',
 'ENSG00000099377',
 'ENSG00000099381',
 'ENSG00000099624',
 'ENSG00000099769',
 'ENSG00000099795',
 'ENSG00000099797',
 'ENSG00000099810',
 'ENSG00000099860',
 'ENSG00000099875',
 'ENSG00000099940',
 'ENSG00000099942',
 'ENSG00000099956',
 'ENSG00000099968',
 'ENSG00000099998',
 'ENSG00000100030',
 'ENSG00000100033',
 'ENSG00000100055',
 'ENSG00000100060',
 'ENSG00000100065',
 'ENSG00000100077',
 'ENSG00000100078',
 'ENSG00000100116',
 'ENSG00000100150',
 'ENSG00000100167',
 'ENSG00000100219',
 'ENSG00000100234',
 'ENSG00000100246',
 'ENSG00000100280',
 'ENSG00000100285',
 'ENSG00000100290',
 'ENSG00000100292',
 'ENSG00000100294',
 'ENSG00000100299',
 'ENSG00000100300',
 'ENSG00000100311',
 'ENSG00000100324',
 'ENSG00000100330',
 'ENSG00000100344',
 'ENSG00000100345',
 'ENSG00000100346',
 'ENSG00000100347',
 'ENSG00000100348',
 'ENSG00000100351',
 'ENSG00000100365',
 'ENSG00000100368',
 'ENSG00000100385',
 'ENSG00000100387',
 'ENSG00000100393',
 'ENSG00000100412',
 'ENSG00000100417',
 'ENSG00000100422',
 'ENSG00000100448',
 'ENSG00000100453',
 'ENSG00000100485',
 'ENSG00000100504',
 'ENSG00000100522',
 'ENSG00000100554',
 'ENSG00000100567',
 'ENSG00000100577',
 'ENSG00000100592',
 'ENSG00000100596',
 'ENSG00000100600',
 'ENSG00000100603',
 'ENSG00000100605',
 'ENSG00000100614',
 'ENSG00000100626',
 'ENSG00000100644',
 'ENSG00000100650',
 'ENSG00000100714',
 'ENSG00000100721',
 'ENSG00000100726',
 'ENSG00000100764',
 'ENSG00000100784',
 'ENSG00000100796',
 'ENSG00000100804',
 'ENSG00000100852',
 'ENSG00000100888',
 'ENSG00000100889',
 'ENSG00000100902',
 'ENSG00000100906',
 'ENSG00000100911',
 'ENSG00000100918',
 'ENSG00000100934',
 'ENSG00000100938',
 'ENSG00000100968',
 'ENSG00000100983',
 'ENSG00000100985',
 'ENSG00000100994',
 'ENSG00000101017',
 'ENSG00000101049',
 'ENSG00000101057',
 'ENSG00000101096',
 'ENSG00000101104',
 'ENSG00000101109',
 'ENSG00000101144',
 'ENSG00000101158',
 'ENSG00000101160',
 'ENSG00000101182',
 'ENSG00000101210',
 'ENSG00000101224',
 'ENSG00000101255',
 'ENSG00000101265',
 'ENSG00000101266',
 'ENSG00000101282',
 'ENSG00000101290',
 'ENSG00000101307',
 'ENSG00000101310',
 'ENSG00000101333',
 'ENSG00000101335',
 'ENSG00000101336',
 'ENSG00000101347',
 'ENSG00000101365',
 'ENSG00000101384',
 'ENSG00000101407',
 'ENSG00000101412',
 'ENSG00000101421',
 'ENSG00000101444',
 'ENSG00000101460',
 'ENSG00000101473',
 'ENSG00000101493',
 'ENSG00000101558',
 'ENSG00000101577',
 'ENSG00000101608',
 'ENSG00000101665',
 'ENSG00000101670',
 'ENSG00000101680',
 'ENSG00000101695',
 'ENSG00000101773',
 'ENSG00000101844',
 'ENSG00000101846',
 'ENSG00000101849',
 'ENSG00000101888',
 'ENSG00000101911',
 'ENSG00000101916',
 'ENSG00000101945',
 'ENSG00000101966',
 'ENSG00000101974',
 'ENSG00000102001',
 'ENSG00000102032',
 'ENSG00000102096',
 'ENSG00000102125',
 'ENSG00000102144',
 'ENSG00000102172',
 'ENSG00000102181',
 'ENSG00000102230',
 'ENSG00000102245',
 'ENSG00000102287',
 'ENSG00000102302',
 'ENSG00000102312',
 'ENSG00000102393',
 'ENSG00000102524',
 'ENSG00000102554',
 'ENSG00000102575',
 'ENSG00000102580',
 'ENSG00000102606',
 'ENSG00000102699',
 'ENSG00000102710',
 'ENSG00000102753',
 'ENSG00000102755',
 'ENSG00000102760',
 'ENSG00000102780',
 'ENSG00000102858',
 'ENSG00000102871',
 'ENSG00000102882',
 'ENSG00000102886',
 'ENSG00000102890',
 'ENSG00000102893',
 'ENSG00000102962',
 'ENSG00000102967',
 'ENSG00000102981',
 'ENSG00000102996',
 'ENSG00000103024',
 'ENSG00000103056',
 'ENSG00000103066',
 'ENSG00000103091',
 'ENSG00000103126',
 'ENSG00000103148',
 'ENSG00000103150',
 'ENSG00000103197',
 'ENSG00000103202',
 'ENSG00000103257',
 'ENSG00000103319',
 'ENSG00000103342',
 'ENSG00000103415',
 'ENSG00000103479',
 'ENSG00000103485',
 'ENSG00000103489',
 'ENSG00000103490',
 'ENSG00000103496',
 'ENSG00000103502',
 'ENSG00000103522',
 'ENSG00000103653',
 'ENSG00000103707',
 'ENSG00000103769',
 'ENSG00000103811',
 'ENSG00000103876',
 'ENSG00000103942',
 'ENSG00000104067',
 'ENSG00000104142',
 'ENSG00000104205',
 'ENSG00000104290',
 'ENSG00000104312',
 'ENSG00000104321',
 'ENSG00000104331',
 'ENSG00000104332',
 'ENSG00000104365',
 'ENSG00000104368',
 'ENSG00000104375',
 'ENSG00000104388',
 'ENSG00000104408',
 'ENSG00000104432',
 'ENSG00000104518',
 'ENSG00000104522',
 'ENSG00000104524',
 'ENSG00000104549',
 'ENSG00000104687',
 'ENSG00000104689',
 'ENSG00000104691',
 'ENSG00000104695',
 'ENSG00000104763',
 'ENSG00000104765',
 'ENSG00000104812',
 'ENSG00000104814',
 'ENSG00000104825',
 'ENSG00000104835',
 'ENSG00000104856',
 'ENSG00000104879',
 'ENSG00000104880',
 'ENSG00000104881',
 'ENSG00000104885',
 'ENSG00000104892',
 'ENSG00000104899',
 'ENSG00000104903',
 'ENSG00000104915',
 'ENSG00000104921',
 'ENSG00000104946',
 'ENSG00000104951',
 'ENSG00000104953',
 'ENSG00000104972',
 'ENSG00000104974',
 'ENSG00000104998',
 'ENSG00000105122',
 'ENSG00000105131',
 'ENSG00000105136',
 'ENSG00000105173',
 'ENSG00000105220',
 'ENSG00000105221',
 'ENSG00000105223',
 'ENSG00000105229',
 'ENSG00000105245',
 'ENSG00000105281',
 'ENSG00000105287',
 'ENSG00000105289',
 'ENSG00000105325',
 'ENSG00000105327',
 'ENSG00000105329',
 'ENSG00000105357',
 'ENSG00000105369',
 'ENSG00000105393',
 'ENSG00000105397',
 'ENSG00000105426',
 'ENSG00000105429',
 'ENSG00000105443',
 'ENSG00000105464',
 'ENSG00000105483',
 'ENSG00000105497',
 'ENSG00000105499',
 'ENSG00000105538',
 'ENSG00000105552',
 'ENSG00000105568',
 'ENSG00000105607',
 'ENSG00000105609',
 'ENSG00000105639',
 'ENSG00000105649',
 'ENSG00000105655',
 'ENSG00000105656',
 'ENSG00000105664',
 'ENSG00000105695',
 'ENSG00000105701',
 'ENSG00000105708',
 'ENSG00000105711',
 'ENSG00000105723',
 'ENSG00000105750',
 'ENSG00000105755',
 'ENSG00000105810',
 'ENSG00000105835',
 'ENSG00000105851',
 'ENSG00000105855',
 'ENSG00000105877',
 'ENSG00000105928',
 'ENSG00000105929',
 'ENSG00000105953',
 'ENSG00000105971',
 'ENSG00000105974',
 'ENSG00000105976',
 'ENSG00000105989',
 'ENSG00000106003',
 'ENSG00000106018',
 'ENSG00000106049',
 'ENSG00000106052',
 'ENSG00000106070',
 'ENSG00000106089',
 'ENSG00000106100',
 'ENSG00000106123',
 'ENSG00000106211',
 'ENSG00000106258',
 'ENSG00000106278',
 'ENSG00000106299',
 'ENSG00000106327',
 'ENSG00000106348',
 'ENSG00000106366',
 'ENSG00000106367',
 'ENSG00000106392',
 'ENSG00000106397',
 'ENSG00000106404',
 'ENSG00000106459',
 'ENSG00000106462',
 'ENSG00000106483',
 'ENSG00000106526',
 'ENSG00000106546',
 'ENSG00000106571',
 'ENSG00000106605',
 'ENSG00000106615',
 'ENSG00000106617',
 'ENSG00000106636',
 'ENSG00000106683',
 'ENSG00000106692',
 'ENSG00000106733',

In [77]:
out = filter_genes_by_ensg(
    X = cortex.X,
    names = cortex.var.index,
    name2ensg = name2ensg,
    ensg_filter = kegg.ensg,

)

In [78]:
cortex.X.shape

(3005, 19972)

In [79]:
out[0].shape

(3005, 3692)

In [80]:
out[1].shape

(3692,)

In [81]:
out[2].shape

(3692,)

In [82]:
cortex.obs

      labels  precise_labels          cell_type
0          2               0       interneurons
1          2               0       interneurons
2          2               0       interneurons
3          2               0       interneurons
4          2               0       interneurons
...      ...             ...                ...
3000       1               8  endothelial-mural
3001       1               8  endothelial-mural
3002       1               8  endothelial-mural
3003       1               8  endothelial-mural
3004       1               8  endothelial-mural

[3005 rows x 3 columns]

In [85]:
cortex.obs[['labels','cell_type']].drop_duplicates()

      labels             cell_type
0          2          interneurons
290        6          pyramidal SS
468        5         pyramidal CA1
1628       4      oligodendrocytes
2448       3             microglia
2546       1     endothelial-mural
2721       0  astrocytes_ependymal

In [89]:
pbmc.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 5489147 stored elements and shape (11990, 3346)>

In [112]:
pbmc.obs

                    n_counts  batch  labels       str_labels
AAACCTGAGCTAGTGG-1    4520.0      0       2      CD4 T cells
AAACCTGCACATTAGC-1    2788.0      0       2      CD4 T cells
AAACCTGCACTGTTAG-1    4667.0      0       1  CD14+ Monocytes
AAACCTGCATAGTAAG-1    4440.0      0       1  CD14+ Monocytes
AAACCTGCATGAACCT-1    3224.0      0       3      CD8 T cells
...                      ...    ...     ...              ...
TTTGGTTTCGCTAGCG-1    6514.0      1       1  CD14+ Monocytes
TTTGTCACACTTAACG-1    3293.0      1       3      CD8 T cells
TTTGTCACAGGTCCAC-1    8322.0      1       7         NK cells
TTTGTCAGTTAAGACA-1    2933.0      1       0          B cells
TTTGTCATCCCAAGAT-1    3322.0      1       1  CD14+ Monocytes

[11990 rows x 4 columns]

In [113]:
pbmc.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 5489147 stored elements and shape (11990, 3346)>

In [93]:
pbmc.var

                gene_symbols  n_counts-0  n_counts-1  n_counts
ENSG00000188976        NOC2L      1477.0       718.0    2135.0
ENSG00000187608        ISG15      4014.0      1888.0    5705.0
ENSG00000149527        PLCH2       121.0        41.0     157.0
ENSG00000157881        PANK4       224.0       107.0     326.0
ENSG00000157873     TNFRSF14      3639.0      1683.0    5193.0
...                      ...         ...         ...       ...
ENSG00000183255      PTTG1IP      1483.0       711.0    2127.0
ENSG00000160255        ITGB2     18398.0      8663.0   26353.0
ENSG00000160299         PCNT       312.0       157.0     464.0
ENSG00000160305        DIP2A       832.0       400.0    1191.0
ENSG00000160307        S100B        75.0        49.0     123.0

[3346 rows x 4 columns]

In [91]:
pbmc.obs[pbmc.obs['batch']==1]

                    n_counts  batch  labels       str_labels
AAATGCCTCACCAGGC-1    4035.0      1       0          B cells
ACCCACTTCAGTCAGT-1    2461.0      1       7         NK cells
ACGGCCACAGGGTTAG-1    3618.0      1       1  CD14+ Monocytes
ACTGAGTGTGACCAAG-1    2735.0      1       0          B cells
ACTGATGCAGTCCTTC-1    4304.0      1       1  CD14+ Monocytes
...                      ...    ...     ...              ...
TTTGGTTTCGCTAGCG-1    6514.0      1       1  CD14+ Monocytes
TTTGTCACACTTAACG-1    3293.0      1       3      CD8 T cells
TTTGTCACAGGTCCAC-1    8322.0      1       7         NK cells
TTTGTCAGTTAAGACA-1    2933.0      1       0          B cells
TTTGTCATCCCAAGAT-1    3322.0      1       1  CD14+ Monocytes

[4008 rows x 4 columns]

In [86]:
pbmc.obs[['labels','cell_type']].drop_duplicates()

KeyError: "['cell_type'] not in index"

In [ ]:
# brca = d.TCGA(
#     tcga_project = 'BRCA',
#     tcga_dir = dataset_dir/'tcga',
#     # type_col = 'sample_type',
#     subtype_col = 'paper_BRCA_Subtype_PAM50',
#     drop = ['Normal', 'Primary Tumor', 'Metastatic'],
#     gene_name_path = dataset_dir/'other'/'name2ensg.csv',
#     keep_noname = False,
# )

In [119]:
cortex.obs['cell_type'].value_counts()

cell_type
pyramidal CA1           939
oligodendrocytes        820
pyramidal SS            399
interneurons            290
endothelial-mural       235
astrocytes_ependymal    224
microglia                98
Name: count, dtype: int64

In [122]:
pbmc.obs['str_labels'].value_counts()

str_labels
CD4 T cells          4996
CD14+ Monocytes      2227
B cells              1621
CD8 T cells          1448
Other                 463
NK cells              457
FCGR3A+ Monocytes     351
Dendritic Cells       339
Megakaryocytes         88
Name: count, dtype: int64

In [ ]:
class scviData:
    def __init__(
        self,
        dataset: str,
        dataset_dir: Path | str,

        x_label_col: str,
        x_label_type: Literal['ensg','name'],
        gene_name_path: str|Path,
        y_label_col: str = 'labels',

        keep_noname: bool = False,
        verbose: bool = True
    ):

        # get kwargs
        sig = inspect.signature(type(self).__init__)
        self._orig_kwargs = capture_kwargs(sig, self, dataset, dataset_dir, x_label_col, x_label_type, gene_name_path, y_label_col, keep_noname, verbose)
        self.verbose = verbose

        dataset_dir = Path(dataset_dir)
        self.adata = self._load_adata(dataset, dataset_dir/dataset)
        self.x_names, self.ensg_complete = self._get_x_names(x_label_col, x_label_type, gene_name_path, keep_noname)
        self.x_labels = self.x_names['name'].to_list()
        self.y, self.y_labels = self._get_labels(y_label_col)

    def __str__(self):
        return dict_summary(self.__dict__)

    def _load_adata(self, dataset:str, dataset_dir:str):
        try:
            fn = getattr(scvi.data, dataset)
        except AttributeError:
            raise AttributeError(f"{dataset} not in scvi.data")

        if not callable(fn):
            raise TypeError(f"{dataset} exists but is not callable")

        return fn(dataset_dir)

    def _get_x_names(self, label_col:str, label_type:str, gene_name_path:str|Path, keep_noname:bool):
        # data
        df:pd.DataFrame = self.adata.var.reset_index().copy()
        ref = pd.read_csv(gene_name_path)

        # normalize input
        if label_type == 'name':
            df[label_col] = df[label_col].astype('string').str.lower()
        ref['ensg_key'] = ref['ensg']#.astype('string').str.lower()
        ref['name_key'] = ref['name'].astype('string').str.lower()

        # complete name table
        if label_type == 'ensg':
            ensg2name = (
                pd.Series(ref["name"].to_numpy(), index=ref["ensg_key"])
                .groupby(level=0)
                .last()
            )
            df["ensg"] = df[label_col].astype('string')
            df["name"] = df[label_col].map(ensg2name)

        else:  # x_label_type == 'name'
            name2ensg = (
                pd.Series(ref["ensg"].to_numpy(), index=ref["name_key"])
                .groupby(level=0)
                .last()
            )
            df["name"] = df[label_col].astype('string')
            df["ensg"] = df[label_col].map(name2ensg)

        # get complete list of ensg
        ensg_complete = df['ensg'].drop_duplicates().tolist() if keep_noname else df['ensg'][~df['name'].isna()].drop_duplicates().tolist()

        return df, ensg_complete
    
    def _get_labels(self, y_label_col:str):
        cats = pd.Categorical(self.adata.obs[y_label_col])
        y = torch.tensor(cats.codes)
        y_labels = list(cats.categories)
        return y, y_labels

    def get_counts(self, ensg_filter:list[int]|None=None):
        x = self.adata.X
        if scipy.sparse.issparse(x):
            x = x.toarray()

        # filter
        if ensg_filter is not None:
            keep = self.x_names['ensg'].astype("string").isin(pd.Index(ensg_filter))
            x = x[:, keep.to_numpy()]
            self.x_names = self.x_names.loc[keep]

        # convert to tensor in (b,n,1)
            
        self.x = torch.tensor(x).unsqueeze(-1)

        if self.verbose:
            print('# #### scviData() ####')
            print(dict_summary(self.__dict__))

In [330]:
scdata = scviData(
    dataset='cortex', # cortex, pbmc_dataset
    dataset_dir=dataset_dir / 'scvi',
    x_label_col='index',
    x_label_type='name', # name, ensg
    y_label_col='cell_type',
    gene_name_path=dataset_dir/'other'/'name2ensg.csv',
)
scdata.get_counts()
scdata.x.shape

INFO     File /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/cortex/expression.bin already downloaded
INFO     Loading Cortex data from /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/cortex/expression.bin
INFO     Finished loading Cortex data

/home/mv18gs/miniconda3/envs/thesis_scvi/lib/python3.14/functools.py:982: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

torch.Size([3005, 19972])

In [332]:
scdata.y_labels

['astrocytes_ependymal',
 'endothelial-mural',
 'interneurons',
 'microglia',
 'oligodendrocytes',
 'pyramidal CA1',
 'pyramidal SS']

In [341]:
scdata.x_names

         index     name             ensg
2       fnbp1l   fnbp1l  ENSG00000137942
4       cldn12   cldn12  ENSG00000157224
7       sema3c   sema3c  ENSG00000075223
8         jam2     jam2  ENSG00000154721
9      apbb1ip  apbb1ip  ENSG00000077420
...        ...      ...              ...
19905    rragb    rragb  ENSG00000083750
19919  rps6ka3  rps6ka3  ENSG00000177189
19925    phka2    phka2  ENSG00000044446
19936    ctps2    ctps2  ENSG00000047230
19950     tlr8     tlr8  ENSG00000101916

[3688 rows x 3 columns]

In [355]:
pbmc.obs

                    n_counts  batch  labels       str_labels
AAACCTGAGCTAGTGG-1    4520.0      0       2      CD4 T cells
AAACCTGCACATTAGC-1    2788.0      0       2      CD4 T cells
AAACCTGCACTGTTAG-1    4667.0      0       1  CD14+ Monocytes
AAACCTGCATAGTAAG-1    4440.0      0       1  CD14+ Monocytes
AAACCTGCATGAACCT-1    3224.0      0       3      CD8 T cells
...                      ...    ...     ...              ...
TTTGGTTTCGCTAGCG-1    6514.0      1       1  CD14+ Monocytes
TTTGTCACACTTAACG-1    3293.0      1       3      CD8 T cells
TTTGTCACAGGTCCAC-1    8322.0      1       7         NK cells
TTTGTCAGTTAAGACA-1    2933.0      1       0          B cells
TTTGTCATCCCAAGAT-1    3322.0      1       1  CD14+ Monocytes

[11990 rows x 4 columns]

In [366]:
type(pbmc.X.toarray())

numpy.ndarray

In [362]:
type(cortex.X)

numpy.ndarray

In [361]:
type(pbmc.X)

scipy.sparse._csr.csr_matrix

In [368]:
scdata = scviData(
    dataset='cortex', # cortex, pbmc_dataset
    dataset_dir=dataset_dir / 'scvi',
    x_label_col='index',
    x_label_type='name', # name, ensg
    y_label_col='cell_type',
    gene_name_path=dataset_dir/'other'/'name2ensg.csv',
)

kegg2 = d.KEGG(
    relation_filepath=dataset_dir/'other'/'relation_ohe.csv', 
    counts_data=scdata,
)

dataset2 = d.GraphDataset(scdata, kegg2, kegg2)
_batch = d.get_toy_databatch(dataset, device)

INFO     File /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/cortex/expression.bin already downloaded
INFO     Loading Cortex data from /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/cortex/expression.bin
INFO     Finished loading Cortex data

/home/mv18gs/miniconda3/envs/thesis_scvi/lib/python3.14/functools.py:982: ImplicitModificationWarning: Transforming to str index.
  return dispatch(args[0].__class__)(*args, **kw)

# #### KEGG() ####
# _orig_kwargs             5                        dict
# relation                 (75939, 19)              DataFrame
# ensg                     3688                     list
# pathway_labels           305                      list
# edge_index               (2, 26946)               Tensor (cuda:6)
# edge_attr                (26946, 16)              Tensor (cuda:6)
# edge_labels              16                       list
# pathway_index            (3688, 305)              Tensor (cuda:6)

# #### scviData() ####
# _orig_kwargs             8                        dict
# verbose                  True                     bool
# adata                    AnnData
# x_names                  (3688, 3)                DataFrame
# ensg_complete            14404                    list
# x_labels                 19972                    list
# y                        (3005,)                  Tensor (cuda:6)
# y_labels                 7                        list
# x                        (3005, 3688, 1)          Tensor (cuda:6)

# #### DataWrapper() ####
# counts_params            8                        dict
# edge_params              5                        dict
# pathway_params           NoneType
# x                        (3005, 3688, 1)          Tensor (cuda:6)
# y                        (3005,)                  Tensor (cuda:6)
# x_labels                 19972                    list
# y_labels                 7                        list
# edge_index               (2, 26946)               Tensor (cuda:6)
# edge_attr                (26946, 16)              Tensor (cuda:6)
# edge_labels              16                       list
# pathway_index            (3688, 305)              Tensor (cuda:6)
# pathway_labels           305                      list
# num_samples              3005                     int
# num_nodes                3688                     int
# num_node_features        1                        int
# num_classes              7                        int
# num_edges                26946                    int
# num_edge_features        16                       int
# num_pathways             305                      int


# #### GraphDataset(), Summary ####
# Average node degree      0.1369                   float
# Has isolated nodes       True                     bool
# Has self-loops           True                     bool
# Directionality           directed                 str

In [369]:
scdata = scviData(
    dataset='pbmc_dataset', # cortex, pbmc_dataset
    dataset_dir=dataset_dir / 'scvi',
    x_label_col='index',
    x_label_type='ensg', # name, ensg
    y_label_col='str_labels', # cell_type, str_labels
    gene_name_path=dataset_dir/'other'/'name2ensg.csv',
)

kegg2 = d.KEGG(
    relation_filepath=dataset_dir/'other'/'relation_ohe.csv', 
    counts_data=scdata,
)

dataset2 = d.GraphDataset(scdata, kegg2, kegg2)
_batch = d.get_toy_databatch(dataset, device)

INFO     File /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/gene_info_pbmc.csv already
         downloaded
INFO     File /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc_metadata.pickle already
         downloaded
INFO     File
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc8k/filtered_gene_bc_matrices.ta
         r.gz already downloaded
INFO     Extracting tar file
INFO     Removing extracted data at
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc8k/filtered_gene_bc_matrices
INFO     File
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc4k/filtered_gene_bc_matrices.ta
         r.gz already downloaded
INFO     Extracting tar file
INFO     Removing extracted data at
         /home/mv18gs/Documents/GitHub/pathway_model/datasets/scvi/pbmc_dataset/pbmc4k/filtered_gene_bc_matrices

/home/mv18gs/miniconda3/envs/thesis_scvi/lib/python3.14/site-packages/scvi/data/_built_in_data/_pbmc.py:75: FutureWarning: Use anndata.concat instead of AnnData.concatenate, AnnData.concatenate is deprecated and will be removed in the future. See the tutorial for concat at: https://anndata.readthedocs.io/en/latest/concatenation.html
  adata = pbmc8k.concatenate(pbmc4k)

# #### KEGG() ####
# _orig_kwargs             5                        dict
# relation                 (75939, 19)              DataFrame
# ensg                     1098                     list
# pathway_labels           305                      list
# edge_index               (2, 2117)                Tensor (cuda:6)
# edge_attr                (2117, 16)               Tensor (cuda:6)
# edge_labels              16                       list
# pathway_index            (1098, 305)              Tensor (cuda:6)

# #### scviData() ####
# _orig_kwargs             8                        dict
# verbose                  True                     bool
# adata                    AnnData
# x_names                  (1098, 7)                DataFrame
# ensg_complete            3337                     list
# x_labels                 3346                     list
# y                        (11990,)                 Tensor (cuda:6)
# y_labels                 9                        list
# x                        (11990, 1098, 1)         Tensor (cuda:6)

# #### DataWrapper() ####
# counts_params            8                        dict
# edge_params              5                        dict
# pathway_params           NoneType
# x                        (11990, 1098, 1)         Tensor (cuda:6)
# y                        (11990,)                 Tensor (cuda:6)
# x_labels                 3346                     list
# y_labels                 9                        list
# edge_index               (2, 2117)                Tensor (cuda:6)
# edge_attr                (2117, 16)               Tensor (cuda:6)
# edge_labels              16                       list
# pathway_index            (1098, 305)              Tensor (cuda:6)
# pathway_labels           305                      list
# num_samples              11990                    int
# num_nodes                1098                     int
# num_node_features        1                        int
# num_classes              9                        int
# num_edges                2117                     int
# num_edge_features        16                       int
# num_pathways             305                      int


# #### GraphDataset(), Summary ####
# Average node degree      0.5187                   float
# Has isolated nodes       True                     bool
# Has self-loops           True                     bool
# Directionality           directed                 str